CREATE TABLE IF NOT EXISTS `engineering_discovery_runs` (
 `id` text PRIMARY KEY NOT NULL, `project_id` text NOT NULL, `version_number` integer NOT NULL, `input_fingerprint` text NOT NULL, `output_fingerprint` text NOT NULL, `engine_version` text NOT NULL, `source_count` integer NOT NULL, `observation_count` integer NOT NULL, `status` text NOT NULL, `exhaustive` integer DEFAULT 0 NOT NULL, `superseded_at` text, `created_by` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `engineering_discovery_project_version_idx` ON `engineering_discovery_runs` (`project_id`,`version_number`);
CREATE INDEX IF NOT EXISTS `engineering_discovery_current_idx` ON `engineering_discovery_runs` (`project_id`,`superseded_at`);
CREATE TABLE IF NOT EXISTS `engineering_discovery_sources` (`id` text PRIMARY KEY NOT NULL,`run_id` text NOT NULL,`source_id` text NOT NULL,`source_type` text NOT NULL,`source_file` text,`document_id` text,`checksum` text,`status` text NOT NULL,FOREIGN KEY (`run_id`) REFERENCES `engineering_discovery_runs`(`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `engineering_discovery_source_idx` ON `engineering_discovery_sources` (`run_id`,`source_id`);
CREATE TABLE IF NOT EXISTS `engineering_discovery_facts` (`id` text PRIMARY KEY NOT NULL,`run_id` text NOT NULL,`fact_type` text NOT NULL,`value` text NOT NULL,`normalized_value` text NOT NULL,`confidence` integer NOT NULL,`supporting_sources` integer NOT NULL,`conflicting_sources` integer NOT NULL,`evidence_strength` text NOT NULL,`evidence` text NOT NULL,`review_status` text NOT NULL,FOREIGN KEY (`run_id`) REFERENCES `engineering_discovery_runs`(`id`));
CREATE INDEX IF NOT EXISTS `engineering_discovery_fact_idx` ON `engineering_discovery_facts` (`run_id`,`fact_type`,`review_status`);
CREATE TABLE IF NOT EXISTS `engineering_discovery_conflicts` (`id` text PRIMARY KEY NOT NULL,`run_id` text NOT NULL,`conflict_type` text NOT NULL,`fact_type` text NOT NULL,`evidence_sets` text NOT NULL,`confidence` integer NOT NULL,`required_clarification` text NOT NULL,`review_status` text NOT NULL,FOREIGN KEY (`run_id`) REFERENCES `engineering_discovery_runs`(`id`));
CREATE TABLE IF NOT EXISTS `engineering_discovery_gaps` (`id` text PRIMARY KEY NOT NULL,`run_id` text NOT NULL,`fact_type` text NOT NULL,`confidence` integer NOT NULL,`reason` text NOT NULL,`evidence_searched` text NOT NULL,`matching_impact` text NOT NULL,`pricing_impact` text NOT NULL,`approval_impact` text NOT NULL,`status` text NOT NULL,FOREIGN KEY (`run_id`) REFERENCES `engineering_discovery_runs`(`id`));
CREATE TABLE IF NOT EXISTS `engineering_discovery_clarifications` (`id` text PRIMARY KEY NOT NULL,`run_id` text NOT NULL,`question` text NOT NULL,`reason` text NOT NULL,`evidence_searched` text NOT NULL,`missing_engineering_fact` text NOT NULL,`matching_impact` text NOT NULL,`pricing_impact` text NOT NULL,`technical_approval_impact` text NOT NULL,`status` text NOT NULL,FOREIGN KEY (`run_id`) REFERENCES `engineering_discovery_runs`(`id`));
CREATE TABLE IF NOT EXISTS `engineering_discovery_audit_events` (`id` text PRIMARY KEY NOT NULL,`project_id` text NOT NULL,`run_id` text NOT NULL,`action` text NOT NULL,`previous_value` text,`new_value` text NOT NULL,`reason` text NOT NULL,`actor_user_id` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`),FOREIGN KEY (`run_id`) REFERENCES `engineering_discovery_runs`(`id`));
CREATE INDEX IF NOT EXISTS `engineering_discovery_audit_idx` ON `engineering_discovery_audit_events` (`project_id`,`created_at`);
