CREATE TABLE IF NOT EXISTS `drawing_intake_versions` (
 `id` text PRIMARY KEY NOT NULL,`project_id` text NOT NULL,`document_id` text NOT NULL,`document_version_id` text NOT NULL,`version_number` integer NOT NULL,`input_fingerprint` text NOT NULL,`output_fingerprint` text NOT NULL,`parser_version` text NOT NULL,`status` text NOT NULL,`summary` text NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`superseded_at` text,`created_by` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`),FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`),FOREIGN KEY (`document_version_id`) REFERENCES `document_versions`(`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `drawing_intake_document_version_idx` ON `drawing_intake_versions` (`document_id`,`version_number`);
CREATE INDEX IF NOT EXISTS `drawing_intake_current_idx` ON `drawing_intake_versions` (`document_id`,`superseded_at`);
CREATE TABLE IF NOT EXISTS `drawing_document_classifications` (`id` text PRIMARY KEY NOT NULL,`intake_version_id` text NOT NULL,`classification_type` text NOT NULL,`confidence` integer NOT NULL,`extraction_method` text NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `drawing_document_classification_idx` ON `drawing_document_classifications` (`intake_version_id`,`classification_type`);
CREATE TABLE IF NOT EXISTS `drawing_pages` (`id` text PRIMARY KEY NOT NULL,`intake_version_id` text NOT NULL,`page_number` integer NOT NULL,`width` real,`height` real,`coordinate_mode` text NOT NULL,`classifications` text NOT NULL,`text_count` integer NOT NULL,`source_review_status` text NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`extraction_method` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `drawing_page_number_idx` ON `drawing_pages` (`intake_version_id`,`page_number`);
CREATE TABLE IF NOT EXISTS `drawing_metadata` (`id` text PRIMARY KEY NOT NULL,`intake_version_id` text NOT NULL,`drawing_number` text,`revision` text,`sheet_name` text,`discipline` text,`scale` text,`issue_date` text,`consultant` text,`contractor` text,`client` text,`project_name` text,`sheet_size` text,`confidence` integer NOT NULL,`extraction_method` text NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`));
CREATE INDEX IF NOT EXISTS `drawing_metadata_number_idx` ON `drawing_metadata` (`drawing_number`,`sheet_name`);
CREATE TABLE IF NOT EXISTS `drawing_assets` (`id` text PRIMARY KEY NOT NULL,`intake_version_id` text NOT NULL,`page_id` text NOT NULL,`asset_type` text NOT NULL,`text_content` text,`bounding_box` text,`coordinates_available` integer NOT NULL,`detection_confidence` integer NOT NULL,`detection_method` text NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`),FOREIGN KEY (`page_id`) REFERENCES `drawing_pages`(`id`));
CREATE INDEX IF NOT EXISTS `drawing_assets_page_type_idx` ON `drawing_assets` (`page_id`,`asset_type`);
CREATE TABLE IF NOT EXISTS `drawing_legends` (`id` text PRIMARY KEY NOT NULL,`intake_version_id` text NOT NULL,`page_id` text NOT NULL,`legend_version` text,`confidence` integer NOT NULL,`detection_method` text NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`),FOREIGN KEY (`page_id`) REFERENCES `drawing_pages`(`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `drawing_legend_page_idx` ON `drawing_legends` (`intake_version_id`,`page_id`);
CREATE TABLE IF NOT EXISTS `drawing_legend_entries` (`id` text PRIMARY KEY NOT NULL,`legend_id` text NOT NULL,`sequence` integer NOT NULL,`entry_type` text NOT NULL,`label` text NOT NULL,`description` text,`confidence` integer NOT NULL,`review_status` text DEFAULT 'Needs Review' NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`legend_id`) REFERENCES `drawing_legends`(`id`));
CREATE INDEX IF NOT EXISTS `drawing_legend_entry_search_idx` ON `drawing_legend_entries` (`legend_id`,`label`);
CREATE TABLE IF NOT EXISTS `drawing_search_entries` (`id` text PRIMARY KEY NOT NULL,`intake_version_id` text NOT NULL,`page_id` text NOT NULL,`page_number` integer NOT NULL,`text_content` text NOT NULL,`drawing_number` text,`sheet_name` text,`tags` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`),FOREIGN KEY (`page_id`) REFERENCES `drawing_pages`(`id`));
CREATE INDEX IF NOT EXISTS `drawing_search_page_idx` ON `drawing_search_entries` (`intake_version_id`,`page_number`);
CREATE INDEX IF NOT EXISTS `drawing_search_number_idx` ON `drawing_search_entries` (`drawing_number`,`sheet_name`);
CREATE TABLE IF NOT EXISTS `drawing_intake_audit_events` (`id` text PRIMARY KEY NOT NULL,`project_id` text NOT NULL,`document_id` text NOT NULL,`intake_version_id` text NOT NULL,`action` text NOT NULL,`previous_value` text,`new_value` text NOT NULL,`reason` text NOT NULL,`actor_user_id` text NOT NULL,`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`),FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`),FOREIGN KEY (`intake_version_id`) REFERENCES `drawing_intake_versions`(`id`));
CREATE INDEX IF NOT EXISTS `drawing_intake_audit_idx` ON `drawing_intake_audit_events` (`document_id`,`created_at`);
