import type { CommercialReviewView, CommercialSummaryView } from "./commercial-types";
import { EmptyState, ErrorState, LoadingState, PrerequisiteState } from "../shared/WorkspaceStates";

export function CommercialReviewWorkspace(props: { summary: CommercialSummaryView | null; items: CommercialReviewView[]; loading: boolean; error: string; available: boolean; blocker?: string; onPrerequisite:()=>void; filter: string; search: string; reasons: Record<string,string>; onFilter: (v:string)=>void; onSearch:(v:string)=>void; onReason:(id:string,v:string)=>void; onRefresh:()=>void; onAction:(item:CommercialReviewView, operation:"start"|"decision"|"escalate", outcome?:string)=>void }) {
  return <section className="module-page server-review-workspace"><div className="module-heading"><div><small>STEP 06 · SERVER-CONTROLLED COMMERCIAL REVIEW</small><h1>Commercial review</h1><p>Resolve pricing, assumptions and commercial blockers through governed review decisions.</p></div><span className={props.summary?.readiness === "Ready for Quotation" ? "review-ready" : "review-blocked"}>{props.summary?.readiness || "Checking readiness…"}</span></div>
    {!props.available ? <PrerequisiteState state="WAITING" title="Commercial review is not available yet" detail={props.blocker || "Commercial review starts after governed pricing is available."} action="Open pricing" onAction={props.onPrerequisite}/> : <><div className="review-summary-strip">{[["Total",props.summary?.total||0],["Open",props.summary?.open||0],["In review",props.summary?.inReview||0],["Blocked",props.summary?.blocked||0],["Approved",props.summary?.approved||0]].map(([label,value])=><article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</div>
    <div className="review-queue-controls"><select value={props.filter} onChange={e=>props.onFilter(e.target.value)}><option>All</option><option>Open</option><option>In Review</option><option>Blocked</option><option>Approved</option></select><input aria-label="Search commercial review" value={props.search} onChange={e=>props.onSearch(e.target.value)} placeholder="BOQ item or review reason"/><button onClick={props.onRefresh} disabled={props.loading}>Apply filters</button></div>
    {props.error && <ErrorState message={props.error}/>} {props.loading && <LoadingState label="Loading server review queue…"/>}
    {!props.loading && !props.items.length ? <EmptyState title="No commercial review items match this view"/> : <div className="persistent-review-list">{props.items.map(item=><article key={item.id} className={item.blocking ? "review-card-blocked":""}><header><div><small>{item.priority} · {item.review_type}</small><strong>{item.boq_description || item.review_type}</strong></div><span className={item.status === "Approved" ? "review-ready" : item.blocking ? "review-blocked":"review-pending"}>{item.status}</span></header><p>{item.reason_for_review}</p><dl><div><dt>Required decision</dt><dd>{item.required_decision}</dd></div><div><dt>Authority</dt><dd>{item.required_role}</dd></div></dl><textarea aria-label={`Decision reason ${item.id}`} value={props.reasons[item.id]||""} onChange={e=>props.onReason(item.id,e.target.value)} placeholder="Mandatory evidence-based reason"/><footer><small>Review v{item.version_number}</small><div>{["Open","Assigned","Changes Requested"].includes(item.status)&&<button onClick={()=>props.onAction(item,"start")}>Start review</button>}{item.status === "In Review"&&<><button onClick={()=>props.onAction(item,"decision","Changes Requested")}>Request changes</button><button disabled={item.blocking===1} onClick={()=>props.onAction(item,"decision","Approved")}>Approve Commercial Review</button></>} {! ["Approved","Rejected","Superseded","Cancelled"].includes(item.status)&&<button onClick={()=>props.onAction(item,"escalate")}>Escalate</button>}</div></footer></article>)}</div>}</>}
  </section>;
}
