import type { MatchingBoqItemView, MatchCandidateView, SafetyDecisionView } from "./technical-matching-types";
import { EmptyState, ErrorState, LoadingState } from "../shared/WorkspaceStates";
import { matchingCandidateModel } from "./technical-matching-models.mjs";

export function MatchingWorkspace(props: { items: MatchingBoqItemView[]; requirementCount: number; pendingRequirementCount: number; stageStatus: string; blockers: string[]; onSelect: (id: string) => void; onOpenLibrary: () => void }) {
  return <section className="module-page construction-workspace"><div className="module-heading"><div><small>STEP 05 · PRODUCT MATCHING</small><h1>Review product suggestions</h1><p>{props.items.length} persisted BOQ items · {props.requirementCount} extracted requirements · {props.pendingRequirementCount} awaiting review.</p></div><div className="heading-actions"><button className="secondary-action" onClick={props.onOpenLibrary}>Search Product Library</button></div></div>
    <div className="active-source-banner" role="status"><div><small>CANONICAL MATCHING STATE</small><strong>{props.stageStatus}</strong><p>Matching candidates, confidence, eligibility and safety decisions are read from persisted server records. Historical Discovery Only evidence cannot approve a product.</p></div></div>
    {props.blockers.length > 0 && <div className="approval-blocked" role="alert"><strong>Matching remains blocked</strong><ul>{props.blockers.map((blocker, index) => <li key={index}>{blocker}</li>)}</ul></div>}
    <div className="compliance-table"><table><thead><tr><th>BOQ item</th><th>Description</th><th>Quantity</th><th>Extraction review</th><th></th></tr></thead><tbody>{props.items.map(item => <tr key={item.id}><td>{item.item_number || item.sequence}</td><td><strong>{item.description || "Description missing"}</strong><small>{item.section || "Section not recorded"}</small></td><td>{item.original_quantity || "Missing"} {item.original_unit || ""}</td><td><span className={item.review_status === "Approved" ? "review-ready" : "review-pending"}>{item.review_status}</span></td><td><button onClick={() => props.onSelect(item.id)}>Open candidates</button></td></tr>)}</tbody></table></div>
    {!props.items.length && <EmptyState title="No persisted BOQ items are available" detail="Review the extracted BOQ before matching."/>}
  </section>;
}

export function MatchingCandidateReview(props: { item: MatchingBoqItemView; candidates: MatchCandidateView[]; status: string; loading: boolean; error: string; safetyCandidateId: string | null; safetyDecision: SafetyDecisionView | null; safetyLoading: boolean; safetyError: string; onClose: () => void; onRun: () => void; onOpenSafety: (id: string, recalculate?: boolean) => void; onAcknowledge: () => void; onApprove: () => void }) {
  return <div className="match-overlay" role="dialog" aria-modal="true" aria-labelledby="match-title"><button className="drawer-scrim" onClick={props.onClose} aria-label="Close match suggestions"/><section className="match-panel"><header className="match-header"><div><small>PERSISTENT TECHNICAL MATCHING</small><h2 id="match-title">Product candidates</h2><p>{props.item.description || "BOQ item"}</p></div><button onClick={props.onClose}>×</button></header>
    <div className="match-basis"><span>Engine status</span><strong>{props.loading ? "Loading…" : props.status}</strong></div>{props.error && <ErrorState message={props.error}/>}<div className="preview-actions"><button disabled={props.loading} onClick={props.onRun}>{["Not Started", "Not Ready"].includes(props.status) ? "Start technical matching" : "Re-run matching"}</button></div>
    {props.loading && <LoadingState label="Loading persisted match candidates…"/>}<div className="candidate-list">{props.candidates.map(candidate => { const model = matchingCandidateModel(candidate, props.safetyCandidateId === candidate.id ? props.safetyDecision : null); return <article key={candidate.id} className="candidate-card"><div className="candidate-top"><span>AI Suggested · Rank {candidate.rank}</span><b className={model.discoveryOnly ? "confidence-discovery" : "confidence-high"}>{candidate.confidence_state}</b></div><h3>{candidate.manufacturer} · {candidate.part_number}</h3><p>{candidate.family || "Unclassified family"}</p><strong>{candidate.technical_status} · fit {candidate.confidence_score}%</strong><div className="evidence"><span>Matching basis</span><p>{candidate.matchingBasis.join(" · ") || "No verified matching basis"}</p></div>{candidate.mandatoryFailures.length > 0 && <div className="evidence"><span>Mismatches / missing evidence</span><p>{candidate.mandatoryFailures.map((entry) => typeof entry === "string" ? entry : JSON.stringify(entry)).join(" · ")}</p></div>}<div className="evidence"><span>Engineering explanation</span><p>{candidate.explanation}</p></div><p className="audit-note">Engineer Review Required — AI suggestion is not product approval.</p>{model.discoveryOnly && <div className="approval-blocked"><strong>Discovery Only — technical approval prohibited</strong></div>}<button onClick={() => props.onOpenSafety(candidate.id)} disabled={props.safetyLoading && props.safetyCandidateId === candidate.id}>Select Product for governed engineer review</button>
      {props.safetyCandidateId === candidate.id && props.safetyError && <ErrorState message={props.safetyError}/>} {props.safetyCandidateId === candidate.id && props.safetyDecision && <div className="safety-decision-card"><div className="candidate-top"><span>Decision v{props.safetyDecision.version_number}</span><b className={props.safetyDecision.safety_state === "Approval Ready" ? "confidence-high" : "confidence-discovery"}>{props.safetyDecision.safety_state}</b></div><strong>{props.safetyDecision.confidence_level} · {props.safetyDecision.overall_confidence}%</strong><p>{props.safetyDecision.compliance_state} · {props.safetyDecision.technical_eligibility}</p><p>{props.safetyDecision.explanation}</p>{props.safetyDecision.blocks.length > 0 && <div className="approval-blocked"><ul>{props.safetyDecision.blocks.map(block => <li key={block.id}><b>{block.code}</b> — {block.user_message}</li>)}</ul></div>}{props.safetyDecision.warnings.length > 0 && <div className="existing-boq-warning"><ul>{props.safetyDecision.warnings.map(warning => <li key={warning.id}>{warning.message}</li>)}</ul>{props.safetyDecision.warnings.some(warning => !warning.acknowledged_at) && <button onClick={props.onAcknowledge}>Acknowledge warnings with reason</button>}</div>}<div className="preview-actions"><button className="secondary-product" onClick={() => props.onOpenSafety(candidate.id, true)}>Recalculate from current records</button><button disabled={!model.approvalEligible} onClick={props.onApprove}>Approve Product Match</button></div></div>}
    </article>;})}{!props.loading && !props.candidates.length && <EmptyState title="No persisted candidate result" detail="The engine returns No Match instead of inventing a product."/>}</div><p className="audit-note">Pricing remains isolated in Costing and Supplier RFQs.</p></section></div>;
}
