"use client";

import { useEffect, useState } from "react";
import type { PreSalesWorkflow, QuotationView } from "./commercial-types";
import { quotationActionState } from "./commercial-models.mjs";

type CommercialTotal = { amount?:number; currency?:string; state?:string };
export function QuotationWorkspace(props: { projectId:string; projectName:string; workflow:PreSalesWorkflow|null; quotation:QuotationView|null; stale:boolean; loading:boolean; reason:string; onReason:(v:string)=>void; onDraft:()=>void; onApprove:()=>void; onIssue:()=>void; money:(v:number)=>string }) {
  const [commercial,setCommercial]=useState<Record<string,CommercialTotal>|null>(null);
  useEffect(()=>{if(!props.projectId)return;let active=true;fetch(`/api/pricing/projects/${encodeURIComponent(props.projectId)}/commercial-summary`,{credentials:"same-origin"}).then(async response=>{if(!response.ok)throw new Error("Commercial summary unavailable");return response.json();}).then(payload=>{if(active)setCommercial(payload.commercialSummary||null);}).catch(()=>{if(active)setCommercial(null);});return()=>{active=false;};},[props.projectId,props.quotation?.status]);
  const actions=quotationActionState(props.workflow,props.quotation,props.stale);
  const value=(key:string,fallback:string)=>{const entry=commercial?.[key];return entry&&Number.isFinite(entry.amount)?`${entry.currency||"SAR"} ${props.money(Number(entry.amount))}`:fallback;};
  return <section className="module-page server-quotation-workspace"><div className="module-heading"><div><small>STEP 07 · SERVER-GOVERNED CLIENT OUTPUT</small><h1>Quotation</h1><p>Readiness, revision, approval and issue status come only from the canonical workflow.</p></div><span className={props.workflow?.readyForQuotation?"review-ready":"review-blocked"}>{props.workflow?.readyForQuotation?"Ready for governed draft":"Not ready"}</span></div>
    <div className="approval-gate"><strong>{props.workflow?.readyForQuotation ? "Quotation prerequisites satisfied" : "Quotation is blocked"}</strong><p>{props.workflow?.blockers?.length ? props.workflow.blockers.map(b=>b.message).join(" · ") : "No canonical blocker is reported."}</p></div>
    <div className="quotation-revision-control"><div><small>AUTHORITATIVE REVISION</small><h2>{props.quotation ? `Revision ${props.quotation.revision_number||props.quotation.revisionNumber} · ${props.quotation.status}` : props.stale ? "Previous revision is stale" : "No governed quotation revision"}</h2><p>{props.stale?"Evidence changed; the previous revision cannot be approved or issued.":"Browser totals and local approvals do not control this status."}</p></div>{props.quotation?.status==="Draft"&&<textarea value={props.reason} onChange={e=>props.onReason(e.target.value)} placeholder="Mandatory approval reason"/>}<div className="revision-actions">{(!props.quotation||props.stale)&&<button disabled={!actions.canDraft||props.loading} onClick={props.onDraft}>Create governed draft</button>}{props.quotation?.status==="Draft"&&<button disabled={!actions.canApprove||!props.reason.trim()||props.loading} onClick={props.onApprove}>Approve Final Quotation</button>}{props.quotation?.status==="Approved"&&<button disabled={!actions.canIssue||props.loading} onClick={props.onIssue}>Issue approved revision</button>}</div></div>
    <div className="review-summary-strip"><article><small>Draft Calculated Total</small><strong>{value("draftCalculated","Not calculated")}</strong></article><article><small>Technically Eligible Total</small><strong>{value("technicallyEligible","Not eligible")}</strong></article><article><small>Commercially Approved Total</small><strong>{value("commerciallyApproved","Not approved")}</strong></article><article><small>Quotation Approved Total</small><strong>{value("quotationApproved","Not approved")}</strong></article></div>
    <p className="review-server-note">Ready for quotation: {String(Boolean(props.workflow?.readyForQuotation))} · Ready for issue: {String(Boolean(props.workflow?.readyForIssue))}. Actions remain disabled unless the canonical server workflow permits them.</p>
  </section>;
}
