"use client";

import { useEffect, useState } from "react";
import type { PreSalesWorkflow, QuotationView } from "./commercial-types";
import { quotationActionState } from "./commercial-models.mjs";
import { aiQuotationAvailability } from "../../lib/project-navigation.mjs";
import { PrerequisiteState } from "../shared/WorkspaceStates";

type CommercialTotal = { amount?:number; currency?:string; state?:string };
type AdvisoryStatement = { text:string; classification:"FACT"|"DERIVED"|"AI_SUGGESTION"|"MISSING"; evidenceReferences:string[] };
type AiAdvisory = { id:string; status:string; stale:boolean; provider?:string; model?:string; created_at?:string; advisory:Record<string,AdvisoryStatement[]> };
export function QuotationWorkspace(props: { projectId:string; projectName:string; workflow:PreSalesWorkflow|null; quotation:QuotationView|null; stale:boolean; loading:boolean; reason:string; onReason:(v:string)=>void; onDraft:()=>void; onApprove:()=>void; onIssue:()=>void; onOpenRoute:(route:string)=>void; money:(v:number)=>string }) {
  const [commercial,setCommercial]=useState<Record<string,CommercialTotal>|null>(null);
  const [aiAdvisory,setAiAdvisory]=useState<AiAdvisory|null>(null);
  const [aiLoading,setAiLoading]=useState(false);
  const [aiMessage,setAiMessage]=useState("");
  useEffect(()=>{if(!props.projectId)return;let active=true;fetch(`/api/pricing/projects/${encodeURIComponent(props.projectId)}/commercial-summary`,{credentials:"same-origin"}).then(async response=>{if(!response.ok)throw new Error("Commercial summary unavailable");return response.json();}).then(payload=>{if(active)setCommercial(payload.commercialSummary||null);}).catch(()=>{if(active)setCommercial(null);});return()=>{active=false;};},[props.projectId,props.quotation?.status]);
  useEffect(()=>{if(!props.projectId)return;let active=true;fetch(`/api/projects/${encodeURIComponent(props.projectId)}/ai-quotation`,{credentials:"same-origin"}).then(async response=>{if(!response.ok)throw new Error("AI advisory unavailable");return response.json();}).then(payload=>{if(active)setAiAdvisory(payload.advisory||null);}).catch(()=>{if(active)setAiAdvisory(null);});return()=>{active=false;};},[props.projectId,props.quotation?.status]);
  const generateAdvisory=async()=>{setAiLoading(true);setAiMessage("");try{const response=await fetch(`/api/projects/${encodeURIComponent(props.projectId)}/ai-quotation/run`,{method:"POST",credentials:"same-origin"}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||"AI advisory could not be generated.");setAiAdvisory(payload.advisory);setAiMessage(payload.idempotent?"Current advisory reused.":"Advisory generated for engineer review.");}catch(error){setAiMessage(error instanceof Error?error.message:"AI advisory unavailable.");}finally{setAiLoading(false);}};
  const actions=quotationActionState(props.workflow,props.quotation,props.stale);
  const aiAvailability=aiQuotationAvailability(props.workflow);
  const value=(key:string,fallback:string)=>{const entry=commercial?.[key];return entry&&Number.isFinite(entry.amount)?`${entry.currency||"SAR"} ${props.money(Number(entry.amount))}`:fallback;};
  return <section className="module-page server-quotation-workspace"><div className="module-heading"><div><small>STEP 07 · PREPARE QUOTATION</small><h1>Prepare Quotation</h1><p>Create, approve and issue a quotation after the project evidence gates are complete.</p></div><span className={props.workflow?.readyForQuotation?"review-ready":"review-blocked"}>{props.workflow?.readyForQuotation?"Ready for draft":"Not ready"}</span></div>
    <div className="approval-gate"><strong>{props.workflow?.readyForQuotation ? "Quotation prerequisites satisfied" : "Quotation is blocked"}</strong><p>{props.workflow?.blockers?.length ? props.workflow.blockers.map(b=>b.message).join(" · ") : "No blocker is reported."}</p></div>
    {!props.workflow?.readyForQuotation&&!props.quotation ? <PrerequisiteState state="BLOCKED" statusLabel="Blocked" title="Quotation cannot be drafted yet" detail={props.workflow?.blockers?.[0]?.message || "Technical, pricing and final-review prerequisites must be completed."} action="Open prerequisite" onAction={()=>props.onOpenRoute(props.workflow?.blockers?.[0]?.route||"Costing")}/> : <><div className="quotation-revision-control"><div><small>QUOTATION REVISION</small><h2>{props.quotation ? `Revision ${props.quotation.revision_number||props.quotation.revisionNumber} · ${props.quotation.status}` : props.stale ? "Previous revision is stale" : "No quotation revision"}</h2><p>{props.stale?"Project evidence changed; refresh the quotation before approval or issue.":"All approval stages remain independent."}</p></div>{props.quotation?.status==="Draft"&&<textarea value={props.reason} onChange={e=>props.onReason(e.target.value)} placeholder="Mandatory approval reason"/>}<div className="revision-actions">{(!props.quotation||props.stale)&&<button disabled={!actions.canDraft||props.loading} onClick={props.onDraft}>Create draft</button>}{props.quotation?.status==="Draft"&&<button disabled={!actions.canApprove||!props.reason.trim()||props.loading} onClick={props.onApprove}>Approve Final Quotation</button>}{props.quotation?.status==="Approved"&&<button disabled={!actions.canIssue||props.loading} onClick={props.onIssue}>Issue approved revision</button>}</div></div><div className="review-summary-strip"><article><small>Draft Calculated Total</small><strong>{value("draftCalculated","Not calculated")}</strong></article><article><small>Technically Eligible Total</small><strong>{value("technicallyEligible","Not eligible")}</strong></article><article><small>Commercially Approved Total</small><strong>{value("commerciallyApproved","Not approved")}</strong></article><article><small>Quotation Approved Total</small><strong>{value("quotationApproved","Not approved")}</strong></article></div></>}
    <section className="quotation-revision-control ai-quotation-advisory"><div><small>AI QUOTATION ENGINEER · ADVISORY ONLY</small><h2>{aiAvailability.available?"Requires engineer review":"Unavailable until quotation evidence exists"}</h2><p>{aiAvailability.available?"This assistant does not approve the quotation or modify terms, exclusions, products, prices, or workflow state.":aiAvailability.reason}</p>{aiAdvisory&&<p>{aiAdvisory.stale?"Project changed — refresh advisory":`Current${aiAdvisory.created_at?` · ${new Date(aiAdvisory.created_at).toLocaleString()}`:""}`}</p>}</div><div className="revision-actions"><button disabled={aiLoading||!aiAvailability.available} onClick={generateAdvisory}>{aiLoading?"Generating…":aiAdvisory?"Refresh advisory":"Generate AI advisory"}</button>{!aiAvailability.available&&<button className="secondary-action" onClick={()=>props.onOpenRoute(aiAvailability.route)}>Open prerequisite</button>}</div>{aiMessage&&<p className="review-server-note">{aiMessage}</p>}{aiAdvisory&&!aiAdvisory.stale&&<div className="ai-advisory-sections">{Object.entries(aiAdvisory.advisory||{}).map(([section,statements])=>statements.length?<article key={section}><h3>{section.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}</h3>{statements.map((statement,index)=><div key={`${section}-${index}`}><span className="review-pending">{statement.classification}</span><p>{statement.text}</p>{statement.evidenceReferences.length>0&&<small>Evidence: {statement.evidenceReferences.join(" · ")}</small>}</div>)}</article>:null)}</div>}</section>
  </section>;
}
