import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildProductSearchProfile, productRankingCandidateFingerprint, rankProductCandidates, validateProductRanking } from "../app/domain/ai-product-ranking-engine.mjs";
import { generateCandidates } from "../app/domain/product-matching-engine.mjs";
import { deriveEstimatorRowReadiness } from "../app/domain/estimator-row-readiness.mjs";
import { runEstimatorProductMatchingBatch } from "../worker/product-matching-api.mjs";

const fact=(value,origin="INFERRED",confidence=80)=>({value,origin,confidence});
const candidate=(id="p1",overrides={})=>({product:{id,manufacturer:"Honeywell",partNumber:`PN-${id}`,family:"Smoke Detector",description:"Addressable smoke detector",source:{documentId:"doc1",row:4}},score:80,matchingBasis:["Product Family"],comparisons:[],mandatoryFailures:[],technicalStatus:"Technically Compliant",...overrides});
const output=(id="p1",overrides={})=>({recommendationState:"CANDIDATES_READY_FOR_REVIEW",candidates:[{candidateId:id,rank:1,fitScore:82,matchState:"POSSIBLE",matchedCriteria:["Product Family"],mismatchedCriteria:[],missingEvidence:[],explanation:"Candidate fits the supplied retrieval basis.",engineerReviewNotes:"Confirm against source evidence.",...overrides}]});

test("latest understanding projects into evidence-labelled search fields",()=>{const profile=buildProductSearchProfile({boqItem:{id:"b1",description:"Smoke detector"},understanding:{normalizedDescription:fact("Addressable smoke detector"),system:fact("Fire Alarm"),productFamily:fact("Smoke Detector"),attributes:{technology:fact("Addressable")}}});assert.equal(profile.productFamily.value,"Smoke Detector");assert.equal(profile.requiredAttributes.technology.origin,"INFERRED")});
test("AI cannot invent a candidate",()=>assert.throws(()=>validateProductRanking(output("invented"),[candidate()]),/unknown/i));
test("AI cannot invent a part number",()=>assert.throws(()=>validateProductRanking(output("p1",{partNumber:"FAKE-1"}),[candidate()]),/Unsafe/));
test("AI cannot introduce price",()=>assert.throws(()=>validateProductRanking(output("p1",{price:10}),[candidate()]),/Unsafe/));
test("AI cannot approve or select a product",()=>assert.throws(()=>validateProductRanking(output("p1",{approved:true}),[candidate()]),/Unsafe/));
test("unsupported certification or compatibility evidence fails validation",()=>assert.throws(()=>validateProductRanking(output("p1",{matchedCriteria:["UL listed"]}),[candidate()]),/unsupported/));
test("exact part-number retrieval outranks fuzzy retrieval",()=>{const profile={boqItem:{description:"smoke detector",partNumber:"PN-p1"}};const rows=generateCandidates({profile,products:[candidate("p2").product,candidate("p1").product]});assert.equal(rows.candidates[0].product.id,"p1");assert.equal(rows.candidates[0].stage,"Exact Identity")});
test("manufacturer and family retrieval is deterministic",()=>{const profile={boqItem:{description:"detector",manufacturer:"Honeywell",productFamily:"Smoke Detector"}};const rows=generateCandidates({profile,products:[candidate("p1").product,candidate("p2",{product:{...candidate("p2").product,manufacturer:"Other"}}).product]});assert.equal(rows.candidates[0].stage,"Manufacturer Family")});
test("required-attribute contradiction remains surfaced to AI as missing evidence",()=>{const row=candidate("p1",{mandatoryFailures:[{result:"Fail"}]});assert.throws(()=>validateProductRanking(output("p1",{missingEvidence:[] ,matchedCriteria:["Product Family","unsupported"]}),[row]),/unsupported/)});
test("missing specifications do not block product search projection",()=>{const profile=buildProductSearchProfile({boqItem:{id:"b1",description:"Smoke detector"},understanding:{normalizedDescription:fact("Smoke detector"),productFamily:fact("Smoke Detector")}});assert.equal(profile.standards.length,0);assert.equal(profile.productFamily.value,"Smoke Detector")});
test("AI ranking alone leaves readiness in REVIEW when other essentials exist",()=>{const result=deriveEstimatorRowReadiness({boqItemId:"b1",description:"Detector",numericQuantity:1,normalizedUnit:"EA",candidateId:"c1",productId:"p1",candidateReviewStatus:"Needs Review",confidenceState:"Possible",priceRecordId:"price1",priceApprovalStatus:"Approved",priceDownstreamUse:"Costing",priceValidUntil:"2099-01-01",unitCostMinor:100});assert.equal(result.status,"REVIEW");assert.equal(result.product.confirmed,false)});
test("engineer confirmation can feed existing readiness without AI authority",()=>{const result=deriveEstimatorRowReadiness({boqItemId:"b1",description:"Detector",numericQuantity:1,normalizedUnit:"EA",candidateId:"c1",productId:"p1",candidateReviewStatus:"Confirmed",priceRecordId:"price1",priceApprovalStatus:"Approved",priceDownstreamUse:"Costing",priceValidUntil:"2099-01-01",unitCostMinor:100});assert.equal(result.status,"READY")});
test("one failed matching row does not fail the batch",async()=>{const result=await runEstimatorProductMatchingBatch({}, {itemIds:["good","bad"],user:{id:"u1"},execute:async(_env,{itemId})=>{if(itemId==="bad")throw Object.assign(new Error("bad row"),{code:"AI_RANKING_INVALID"});return {status:"Needs Review"}}});assert.deepEqual(result.summary,{total:2,successful:1,failed:1});assert.equal(result.items[1].error.code,"AI_RANKING_INVALID")});
test("invalid AI output fails one ranking closed",async()=>{const result=await rankProductCandidates({searchProfile:{boqItemId:"b1"},candidates:[candidate()],provider:{interpret:async()=>output("unknown")}});assert.equal(result.status,"FAILED");assert.equal(result.validated,null)});
test("unchanged candidate evidence has a stable fingerprint",()=>assert.equal(productRankingCandidateFingerprint([candidate()]),productRankingCandidateFingerprint([candidate()])));
test("changed candidate evidence invalidates the fingerprint",()=>assert.notEqual(productRankingCandidateFingerprint([candidate()]),productRankingCandidateFingerprint([candidate("p1",{product:{...candidate().product,source:{documentId:"doc2"}}})])));
test("frontend contains no server AI token and labels suggestions as non-authoritative",()=>{const page=fs.readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8");const api=fs.readFileSync(new URL("../worker/product-matching-api.mjs",import.meta.url),"utf8");assert.doesNotMatch(page,/CLOUDFLARE_AI_API_TOKEN/);assert.match(api,/AI Suggested/);assert.match(api,/Engineer Review Required/)});
