import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFile } from "node:fs/promises";
import { buildControlledRetryManifest, authorizeControlledRetryRequest, validateControlledRetryRequest, runUnderstandingBatch } from "../worker/estimator-understanding-api.mjs";

const references = ["27.06.16", "27.06.17", "27.06.10", "26.5.1", "27.01.16", "27.04.04"];
const historical = references.map((itemReference, index) => ({ boqItemId: `item-${index}`, itemReference, status: index === 1 ? "COMPLETED" : index === 4 ? "FAILED" : "NEEDS_REVIEW", inputFingerprint: `old-${index}`, interpretation: index === 4 ? null : JSON.stringify({ confidence: "LOW" }) }));
const current = references.map((itemReference, index) => ({ boqItemId: `item-${index}`, itemNumber: itemReference, sequence: index + 1, rowType: "BOQ Item", description: `Equipment ${index}`, numericQuantity: 1, normalizedUnit: "No", sourceDocumentId: `document-${index}`, evidenceDocumentVersionId: `version-${index}`, evidenceExtractionVersion: 1, sourceLocation: { sheet: "BOQ", row: index + 2 } }));
const quality = { recommendedRetryItemReferences: references };

test("controlled retry manifest resolves exact persisted IDs and fingerprints current evidence",()=>{const manifest=buildControlledRetryManifest("historical-run",quality,historical,current);assert.deepEqual(manifest.itemIds,current.map(row=>row.boqItemId));assert.equal(manifest.itemCount,6);assert.match(manifest.retryFingerprint,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(manifest.items).includes("item-"),false)});
test("controlled retry request rejects missing extra duplicate reordered stale and client-controlled fields",()=>{const manifest=buildControlledRetryManifest("historical-run",quality,historical,current);const valid={mode:"CONTROLLED_RETRY",historicalRunId:"historical-run",retryFingerprint:manifest.retryFingerprint,itemIds:manifest.itemIds};assert.ok(authorizeControlledRetryRequest(valid,manifest).value);for(const body of [{...valid,itemIds:[]},{...valid,itemIds:[...valid.itemIds,"extra"]},{...valid,itemIds:[valid.itemIds[0],...valid.itemIds.slice(0,5)]},{...valid,itemIds:[...valid.itemIds].reverse()},{...valid,retryFingerprint:"stale"},{...valid,model:"forged"}])assert.ok(authorizeControlledRetryRequest(body,manifest).error);assert.ok(validateControlledRetryRequest(null).error)});
test("current document version extraction row and input changes stale the retry fingerprint",()=>{const first=buildControlledRetryManifest("historical-run",quality,historical,current);for(const changed of [{...current[0],evidenceDocumentVersionId:"changed"},{...current[0],evidenceExtractionVersion:2},{...current[0],description:"Changed evidence"}]){const rows=[changed,...current.slice(1)];assert.notEqual(buildControlledRetryManifest("historical-run",quality,historical,rows).retryFingerprint,first.retryFingerprint)}});
test("missing current row and changed recommendation fail closed",()=>{assert.equal(buildControlledRetryManifest("historical-run",quality,historical,current.slice(1)).error,"CONTROLLED_RETRY_EVIDENCE_STALE");assert.equal(buildControlledRetryManifest("historical-run",{recommendedRetryItemReferences:references.slice(0,5)},historical,current).error,"CONTROLLED_RETRY_RECOMMENDATIONS_CHANGED")});
test("partial item failure is isolated and retry output remains understanding-only",async()=>{let calls=0,saves=0;const provider={metadata:{provider:"cloudflare-workers-ai-binding",model:"@cf/meta/llama-3.1-8b-instruct-fast",modelVersion:"8b"},interpret:async()=>{calls+=1;if(calls===2)throw Object.assign(new Error("safe"),{code:"AI_PROVIDER_ERROR"});return {normalizedDescription:{value:"Equipment","origin":"EXTRACTED",confidence:100},confidence:"LOW"}}};const result=await runUnderstandingBatch(current.slice(0,3),{provider,save:async()=>{saves+=1}});assert.equal(result.summary.processed,3);assert.equal(result.summary.failed,1);assert.equal(saves,3);assert.doesNotMatch(JSON.stringify(result),/product_match|pricing|approval|quotation/i)});
test("database unique invariant prevents duplicate controlled retry runs",async()=>{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON; CREATE TABLE projects(id TEXT PRIMARY KEY); CREATE TABLE organizations(id TEXT PRIMARY KEY); CREATE TABLE users(id TEXT PRIMARY KEY); CREATE TABLE estimator_understanding_runs(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),organization_id TEXT NOT NULL REFERENCES organizations(id),provider TEXT NOT NULL,model TEXT NOT NULL,model_version TEXT NOT NULL,prompt_version TEXT NOT NULL,schema_version TEXT NOT NULL,config_fingerprint TEXT NOT NULL,status TEXT NOT NULL,total_items INTEGER NOT NULL DEFAULT 0,processed_items INTEGER NOT NULL DEFAULT 0,successful_items INTEGER NOT NULL DEFAULT 0,review_items INTEGER NOT NULL DEFAULT 0,failed_items INTEGER NOT NULL DEFAULT 0,requested_by TEXT NOT NULL,started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TEXT);");db.exec(await readFile(new URL("../drizzle/0059_boq_understanding_controlled_retry.sql",import.meta.url),"utf8"));db.exec("INSERT INTO projects VALUES ('p'); INSERT INTO organizations VALUES ('o'); INSERT INTO users VALUES ('u')");const insert=db.prepare("INSERT INTO estimator_understanding_runs(id,project_id,organization_id,provider,model,model_version,prompt_version,schema_version,config_fingerprint,status,requested_by,run_mode,parent_run_id,authorization_fingerprint) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");insert.run("historical","p","o","cloudflare","8b","8b","p","s","c","COMPLETED","u","CONTROLLED_PILOT",null,null);const args=(id)=>[id,"p","o","cloudflare","8b","8b","p","s","c","PROCESSING","u","CONTROLLED_RETRY","historical","fingerprint"];insert.run(...args("retry-1"));assert.throws(()=>insert.run(...args("retry-2")),/UNIQUE constraint/)});
test("retry source and report cannot persist or expose raw provider material",async()=>{const source=await readFile(new URL("../worker/estimator-understanding-api.mjs",import.meta.url),"utf8");assert.match(source,/JSON\.stringify\(\{ usage: record\.usageMetadata \}\)/);assert.doesNotMatch(source,/raw model output|prompt_json|request_headers|credentials/i);for(const forbidden of ["INSERT INTO product_match","INSERT INTO pricing","INSERT INTO review_decisions","INSERT INTO project_quotation"])assert.doesNotMatch(source,new RegExp(forbidden,"i"))});
