import test from "node:test";
import assert from "node:assert/strict";
import { evaluateSafety, validateManualPrice, validateOverride } from "../app/domain/confidence-safety-engine.mjs";

const item = (overrides = {}) => ({ id: "boq-1", projectId: "project-1", system: "Fire Alarm", category: "Detection Device", description: "Addressable smoke detector", unit: "No.", quantity: 20, productFamily: "Addressable Smoke Detector", sourceDocumentId: "doc-1", sourceLocation: { sheet: "BOQ", row: 12 }, extractionConfidence: 96, ...overrides });
const profile = (overrides = {}) => ({ id: "profile-1", versionNumber: 1, readiness: { status: "Ready for Matching" }, confidence: { applicability: 95 }, standards: [{ body: "EN54", number: "7" }], compatibility: [{ targetItem: "Farenhyt protocol" }], accessories: [{ accessory: "Detector base" }], categoryFields: { environment: "Indoor" }, derivedRequirements: [], ...overrides });
const candidate = (overrides = {}) => ({ id: "candidate-1", searchStage: "Structured", technicalStatus: "Technically Compliant", recommendationTier: "Recommended Candidate", confidence: "High Confidence", product: { id: "p1", partNumber: "IDP-PHOTO-W", reviewStatus: "Reviewed", sourceReliability: "Manufacturer Verified" }, comparisons: [{ pass: true, result: "Pass" }], standards: [{ pass: true, result: "Verified Compliant", evidence: { documentId: "datasheet" } }], compatibility: [{ pass: true, result: "Verified Compatible", evidence: { documentId: "compatibility" } }], accessories: [{ pass: true, result: "Pass" }], lifecycle: { state: "Active", result: "Pass", blocking: false, warning: false }, mandatoryFailures: [], commercialAvailability: "Valid Current Price Available", provenance: { productSource: { documentId: "catalogue" } }, ...overrides });
const provenance = { complete: true, confidence: 100, documentClassificationConfidence: 98, specificationExtractionConfidence: 96 };
const user = { id: "reviewer-1", role: "Technical Reviewer" };
const price = { productId: "p1", candidateId: "candidate-1", approvalStatus: "Approved", sourceId: "quote-1", currency: "SAR", validUntil: "2099-01-01" };
const evaluate = (overrides = {}) => evaluateSafety({ item: item(), profile: profile(), candidate: candidate(), provenance, prices: [price], user, ...overrides });

test("unclassified new BOQ items cannot be high confidence or approve product or price", () => { const result = evaluate({ item: item({ system: "", category: "", description: "New BOQ item", unit: "", quantity: null, productFamily: "", sourceLocation: null }), candidate: candidate({ confidence: "High Confidence" }) }); assert.notEqual(result.confidence.level, "High Confidence"); assert.equal(result.approvalReady, false); assert.equal(result.approvalEligibility.price, "Price Approval Disabled"); });
test("missing quantity disables approval", () => { const result = evaluate({ item: item({ quantity: null }) }); assert.ok(result.blocks.some((entry) => entry.code === "MISSING_QUANTITY")); assert.equal(result.approvalReady, false); });
test("missing unit disables approval", () => { const result = evaluate({ item: item({ unit: "" }) }); assert.ok(result.blocks.some((entry) => entry.code === "MISSING_UNIT")); });
test("missing category specifications forces discovery-safe confidence", () => { const result = evaluate({ profile: profile({ standards: [], compatibility: [], accessories: [], categoryFields: {} }) }); assert.equal(result.safetyState, "Missing Critical Information"); assert.equal(result.confidence.level, "Discovery Only"); });
test("semantic-only candidate cannot become high confidence", () => { const result = evaluate({ candidate: candidate({ searchStage: "Semantic Discovery", recommendationTier: "Discovery Candidate", confidence: "High Confidence" }) }); assert.equal(result.confidence.level, "Discovery Only"); assert.equal(result.approvalReady, false); });
test("missing compatibility evidence cannot be approved", () => { const result = evaluate({ candidate: candidate({ compatibility: [{ pass: false, result: "Evidence Missing" }], mandatoryFailures: [{ type: "Compatibility", result: "Evidence Missing" }] }) }); assert.ok(result.blocks.some((entry) => ["COMPATIBILITY_EVIDENCE_MISSING", "MANDATORY_REQUIREMENT_FAILED"].includes(entry.code))); assert.equal(result.approvalReady, false); });
test("valid price cannot override a technical failure", () => { const result = evaluate({ candidate: candidate({ technicalStatus: "Non-Compliant", mandatoryFailures: [{ type: "Voltage", result: "Fail" }] }) }); assert.equal(result.complianceState, "Non-Compliant"); assert.equal(result.approvalEligibility.price, "Price Approval Disabled"); });
test("expired-only price creates a warning and remains price-disabled", () => { const expired = { ...price, validUntil: "2025-01-01" }; const result = evaluate({ prices: [expired], candidate: candidate({ commercialAvailability: "Expired Price Only" }) }); assert.ok(result.warnings.some((entry) => entry.code === "EXPIRED_PRICE_ONLY")); assert.ok(result.approvalEligibility.priceBlocks.includes("CURRENT_PRICE_SOURCE_REQUIRED")); });
test("prohibited manufacturer is a non-overridable block", () => { const result = evaluate({ candidate: candidate({ mandatoryFailures: [{ type: "Manufacturer", result: "Prohibited" }] }) }); const blocked = result.blocks.find((entry) => entry.code === "PROHIBITED_MANUFACTURER"); assert.equal(blocked.overridable, false); const override = validateOverride({ safetyDecision: result, request: { approvalLevel: 5, blockCodes: [blocked.code], reason: "Project authority exception", technicalJustification: "Authority documented exception", evidence: { documentId: "a" }, scope: "Project", expiresAt: "2099-01-01" }, user: { role: "Admin" } }); assert.equal(override.permitted, false); });
test("discontinued product requires an authorized exception", () => { const result = evaluate({ candidate: candidate({ lifecycle: { state: "Discontinued", result: "Blocked", blocking: true }, mandatoryFailures: [] }) }); assert.ok(result.blocks.some((entry) => entry.code === "LIFECYCLE_BLOCK")); assert.equal(result.approvalReady, false); });
test("critical provenance absence caps confidence and blocks approval", () => { const result = evaluate({ provenance: { ...provenance, complete: false, confidence: 30 } }); assert.equal(result.confidence.level, "Discovery Only"); assert.ok(result.blocks.some((entry) => entry.code === "PROVENANCE_INCOMPLETE")); });
test("confidence uses the weakest critical component instead of an average", () => { const result = evaluate({ provenance: { ...provenance, specificationExtractionConfidence: 35 } }); assert.equal(result.confidence.overall, 35); assert.notEqual(result.confidence.level, "High Confidence"); });
test("compliance, confidence and approval readiness remain independent", () => { const result = evaluate({ user: { id: "estimator", role: "Estimator" } }); assert.equal(result.complianceState, "Compliant"); assert.ok(result.confidence.overall >= 80); assert.equal(result.approvalReady, false); assert.equal(result.approvalEligibility.technical, "Human Review Required"); });
test("critical conflicts and unapproved assumptions block approval", () => { const result = evaluate({ conflicts: [{ blocking: true, status: "Open" }], assumptions: [{ approvalRequired: true, status: "Proposed" }] }); assert.ok(result.blocks.some((entry) => entry.code === "CRITICAL_CONFLICT")); assert.ok(result.blocks.some((entry) => entry.code === "CRITICAL_ASSUMPTION_UNAPPROVED")); });
test("manual pricing requires identity, reason, source, validity, scope, technical approval and audit", () => { const denied = validateManualPrice({ input: { candidateId: "candidate-1", productId: "p1", price: 100, currency: "SAR", projectId: "project-1" }, user: { role: "Procurement" }, technicalApproval: { status: "Approved", candidateId: "candidate-1" } }); assert.equal(denied.permitted, false); assert.ok(denied.missing.includes("sourceId")); assert.equal(denied.auditRequired, true); const allowed = validateManualPrice({ input: { candidateId: "candidate-1", productId: "p1", price: 100, currency: "SAR", sourceId: "quote-1", validUntil: "2099-01-01", reason: "Supplier quotation transcription", projectId: "project-1" }, user: { role: "Procurement" }, technicalApproval: { status: "Approved", candidateId: "candidate-1" } }); assert.equal(allowed.permitted, true); });
test("authorized standard match becomes technically eligible but not price-approved without prior technical approval", () => { const result = evaluate(); assert.equal(result.approvalEligibility.technical, "Eligible for Technical Approval"); assert.equal(result.approvalReady, true); assert.equal(result.approvalEligibility.price, "Price Approval Disabled"); });
