import test from "node:test";
import assert from "node:assert/strict";
import { METRIC_REGISTRY, deriveWorkflow, generateActions, calculateRisks, deriveProjectDashboard } from "../app/domain/dashboard-workflow-engine.mjs";

const completeFacts = { documents: 2, classified: 2, processing: 0, failedJobs: 0, boqItems: 3, extractionReview: 0, specificationExtractions: 1, requirementProfiles: 3, requirementReview: 0, matchedItems: 3, technicalPending: 0, technicalApproved: 3, pricedItems: 3, missingPrices: 0, commercialPending: 0, commercialApproved: 3, finalReviewApproved: 3, openClarifications: 0, blockingClarifications: 0, openSafetyBlocks: 0, exportsCompleted: 0, exportFailures: 0 };

test("project progress changes only with real workflow facts", () => { const empty = deriveWorkflow({}), uploaded = deriveWorkflow({ documents: 1 }), classified = deriveWorkflow({ documents: 1, classified: 1 }); assert.ok(empty.progress < uploaded.progress); assert.ok(uploaded.progress < classified.progress); });
test("blocking conflicts prevent quotation readiness", () => { const result = deriveWorkflow({ ...completeFacts, openSafetyBlocks: 1 }); assert.equal(result.ready, false); assert.ok(result.blockers.some((entry) => /safety block/i.test(entry.message))); });
test("pending technical approval cannot show complete", () => { const result = deriveWorkflow({ ...completeFacts, technicalApproved: 2, technicalPending: 1 }); assert.equal(result.stages.find((s) => s.id === "technical").status, "Needs Review"); assert.equal(result.ready, false); });
test("failed documents generate an exact filtered action", () => { const workflow = deriveWorkflow({ ...completeFacts, failedJobs: 2 }); const action = generateActions({ ...completeFacts, failedJobs: 2 }, workflow, { id: "p1", name: "P" }).find((x) => x.type === "retry-processing"); assert.equal(action.route, "Documents?status=failed"); assert.equal(action.blocking, true); });
test("only technically approved unpriced items drive costing action", () => { const facts = { ...completeFacts, technicalApproved: 3, pricedItems: 1, missingPrices: 2 }; const action = generateActions(facts, deriveWorkflow(facts), { id: "p1" }).find((x) => x.type === "missing-price"); assert.match(action.title, /2 technically approved item/); assert.equal(action.route, "Costing?status=missing-price"); assert.equal(generateActions({ ...facts, technicalApproved: 0 }, deriveWorkflow({ ...facts, technicalApproved: 0 }), { id: "p1" }).some((x) => x.type === "missing-price"), false); });
test("risk indicators always explain trigger and impact", () => { const facts = { ...completeFacts, missingPrices: 3, pricedItems: 0 }; const risks = calculateRisks(facts, deriveWorkflow(facts), { id: "p1", dueDate: "2026-08-04" }, new Date("2026-08-02T00:00:00Z")); assert.ok(risks.length); assert.ok(risks.every((r) => r.trigger && r.impact && r.recommendedAction && r.source)); });
test("commercial totals are hidden from unauthorized roles", () => { const estimator = deriveProjectDashboard({ facts: completeFacts, project: { id: "p1" }, role: "Estimator", totals: { quotedValue: 100 } }); const commercial = deriveProjectDashboard({ facts: completeFacts, project: { id: "p1" }, role: "Commercial Reviewer", totals: { quotedValue: 100 } }); assert.equal(estimator.totals, undefined); assert.equal(estimator.commercialRestricted, true); assert.equal(commercial.totals.quotedValue, 100); });
test("ready for quotation is derived and cannot be manually falsified", () => { const incomplete = deriveProjectDashboard({ facts: { documents: 1, classified: 1, boqItems: 1 }, project: { id: "p1", manualStatus: "Ready for Quotation" } }); assert.notEqual(incomplete.project.status, "Ready for Quotation"); assert.equal(incomplete.workflow.ready, false); });
test("only terminal business statuses can override derived workflow status", () => { const held = deriveProjectDashboard({ facts: completeFacts, project: { id: "p1", manualStatus: "On Hold" } }); assert.equal(held.project.status, "On Hold"); });
test("metric registry has formal source, permission and drill-down definitions", () => { assert.ok(METRIC_REGISTRY.length >= 10); assert.ok(METRIC_REGISTRY.every((m) => m.id && m.source && m.formula && m.permission && m.route && m.version)); assert.equal(new Set(METRIC_REGISTRY.map((m) => m.id)).size, METRIC_REGISTRY.length); });
