import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";const source=fs.readFileSync(new URL("../app/domain/drawing-symbol-recognition-engine.mjs",import.meta.url),"utf8");
const api=fs.readFileSync(new URL("../worker/drawing-symbol-recognition-api.mjs",import.meta.url),"utf8"),migration=fs.readFileSync(new URL("../drizzle/0033_drawing_symbol_recognition.sql",import.meta.url),"utf8"),ui=fs.readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8");
test("definitions require explicit legend rows",()=>{assert.match(source,/legendRows/);assert.match(source,/Explicit legend row/);assert.doesNotMatch(source,/engineeringDeviceType/);});
test("unknown repeated geometry remains unknown",()=>{assert.match(source,/Repeated vector shape has no explicit legend definition/);assert.match(source,/unknownSymbols/);assert.match(source,/!o\.matchedDefinitionKey/);});
test("occurrences preserve immutable geometry and match basis",()=>{for(const key of ["sourceGeometry","boundingBox","shapeSignature","matchBasis","confidence","reviewStatus"])assert.match(source,new RegExp(key));});
test("versioned persistence is fingerprint-idempotent and project scoped",()=>{assert.match(api,/input_fingerprint/);assert.match(api,/output_fingerprint/);assert.match(api,/previous\?\.input_fingerprint===inputFingerprint/);assert.match(migration,/project_id/);assert.match(migration,/drawing_symbol_source_geometries/);});
test("governed definition and occurrence actions create immutable audit events",()=>{for(const action of ["approve","reject","edit","split","merge","restore"])assert.match(api,new RegExp(action));assert.match(api,/drawing_symbol_review_events/);assert.match(api,/reason\.length<5/);});
test("Symbol Review workspace exposes definitions, occurrences, unknowns, evidence and history",()=>{for(const label of ["Definitions","Occurrences","Unknown symbols","Evidence","Review history"])assert.match(ui,new RegExp(label));assert.match(ui,/symbols/);assert.match(ui,/Occurrences are observations, not BOQ quantities or engineering objects/);});
test("symbol implementation has no downstream matching or pricing writes",()=>{const combined=source+api+migration;assert.doesNotMatch(combined,/INSERT INTO (?:product_match|pricing_)/i);assert.doesNotMatch(combined,/engineering_objects/i);});
