import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";
const engine=await readFile("app/domain/drawing-legend-geometry-engine.mjs","utf8"),api=await readFile("worker/drawing-legend-geometry-api.mjs","utf8"),ui=await readFile("app/page.tsx","utf8"),symbol=await readFile("worker/drawing-symbol-recognition-api.mjs","utf8");
test("captures only native geometry contained by structural symbol cells",()=>{assert.match(engine,/wholly contained in structurally empty symbol cell/);assert.match(engine,/cx>=region\.x/);assert.match(engine,/box\.y>=region\.y/)});
test("preserves paths fills strokes transforms and deterministic signatures",()=>{for(const value of["operators","coordinates","sourceBounds","transform","fill","stroke","geometrySignature"])assert.match(engine,new RegExp(value));assert.match(engine,/SHA-256/)});
test("missing geometry remains blocked",()=>{assert.match(api,/Symbol Geometry Missing/);assert.match(api,/Missing geometry cannot be approved/)});
test("all governed geometry actions are available and audited",()=>{for(const value of["confirm","reject","reassign","split-symbols","merge-fragments","restore"])assert.match(api,new RegExp(value));assert.match(api,/drawing_legend_geometry_review_events/)});
test("approved geometry is versioned and fingerprint idempotent",()=>{assert.match(api,/drawing_legend_geometry_approved_versions/);assert.match(api,/input_fingerprint\s*===\s*input/);assert.match(api,/output_fingerprint\s*===\s*output/)});
test("symbol recognition consumes only approved geometry links",()=>{assert.match(symbol,/drawing_legend_geometry_approved_versions/);assert.match(symbol,/drawing_legend_geometry_approved_links/);assert.match(symbol,/APPROVED_SYMBOL_GEOMETRY_REQUIRED/)});
test("workspace supports deep links and has no downstream creation",()=>{assert.match(ui,/Legend Symbol Geometry/);assert.match(ui,/legendGeometry/);for(const forbidden of[/INSERT INTO engineering_objects/i,/INSERT INTO product_match/i,/INSERT INTO pricing_/i])assert.doesNotMatch(api,forbidden)});
