import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { assembleKnowledgeProfile, createKnowledgeFact, normalizeMeasurement, resolveEffectiveVersion, resolveScopedFacts, scoreRequirementLink, validateRequirementLink } from "../app/domain/engineering-knowledge.mjs";

const provenance = { sourceType: "Specification Clause", sourceId: "req-1", documentId: "doc-1", documentVersionId: "ver-1", clause: "2.1", originalText: "The detector shall be IP66", extractionMethod: "pdfjs-coordinate-layout", parserVersion: "1", confidence: 90, createdAt: "2026-08-01T00:00:00Z" };
test("enforces fact classification, provenance, normalization lineage and AI safety", () => { const source = createKnowledgeFact({ id: "f1", entityType: "Requirement", entityId: "req-1", predicate: "IP Rating", value: "IP 66", factType: "Source Fact", scopeType: "Project", scopeId: "p1", projectId: "p1", provenance }); assert.equal(source.factType, "Source Fact"); assert.throws(() => createKnowledgeFact({ ...source, id: "f2", factType: "Normalized Fact", sourceFactId: null }), /source fact/i); assert.throws(() => createKnowledgeFact({ ...source, id: "f3", factType: "AI Suggestion", status: "Approved" }), /cannot approve/i); });
test("normalizes compatible units while retaining originals and fails closed", () => { assert.deepEqual(normalizeMeasurement({ value: 1500, unit: "mA", targetUnit: "A" }), { originalValue: 1500, originalUnit: "mA", normalizedValue: 1.5, normalizedUnit: "A", status: "Normalized" }); assert.equal(normalizeMeasurement({ value: 12, unit: "V", targetUnit: "A" }).status, "Invalid Conversion"); assert.equal(normalizeMeasurement({ value: 12, unit: "unknown" }).normalizedValue, null); });
test("resolves effective immutable versions", () => { const found = resolveEffectiveVersion([{ id: "old", effectiveFrom: "2025-01-01", effectiveTo: "2026-01-01" }, { id: "current", effectiveFrom: "2026-01-01" }], new Date("2026-08-01")); assert.equal(found.id, "current"); });
test("keeps project overrides scoped and ahead of global rules", () => { const facts = [{ id: "g", scopeType: "Global", status: "Active" }, { id: "p1", scopeType: "Project", scopeId: "project-1", status: "Active" }, { id: "p2", scopeType: "Project", scopeId: "project-2", status: "Active" }]; assert.deepEqual(resolveScopedFacts(facts, { projectId: "project-1" }).map((fact) => fact.id), ["p1", "g"]); });
test("creates suggestions from structured BOQ-to-requirement signals but never confirms them", () => { const link = scoreRequirementLink({ boqItem: { description: "Addressable smoke detector", system: "Fire Alarm", category: "Detection" }, requirement: { originalText: "Addressable smoke detector shall comply", system: "Fire Alarm", category: "Detection", source: {} } }); assert.ok(link.confidence >= 55); assert.notEqual(link.status, "Confirmed"); assert.throws(() => validateRequirementLink({ projectId: "p", boqItemId: "b", requirementId: "r", status: "Confirmed" }), /reviewer/i); });
test("penalizes cross-equipment keyword collisions", () => { const link = scoreRequirementLink({ boqItem: { description: "Loop powered sounder with strobe", system: "Fire Alarm" }, requirement: { originalText: "The fire alarm control panel shall provide alarm verification", system: "Fire Alarm", source: {} } }); assert.ok(link.confidence < 45); assert.ok(link.evidence.some((entry) => entry.includes("Cross-equipment conflict"))); assert.equal(link.assessment, "Uncertain"); });
test("recognizes CCTV and access-control equipment using specific technical terms", () => {
  const fixed = scoreRequirementLink({ boqItem: { description: "Fixed dome camera, 5MP, outdoor" }, requirement: { originalText: "Megapixel Resolution Fixed Cameras shall be fixed Network IP megapixel cameras.", source: {} } });
  const ptz = scoreRequirementLink({ boqItem: { description: "PTZ camera, wall mounted" }, requirement: { originalText: "PTZ Cameras shall be Network IP cameras with dome enclosure.", source: {} } });
  const access = scoreRequirementLink({ boqItem: { description: "SACS door assembly with card reader and door contact" }, requirement: { originalText: "Door hardware equipment includes card readers and door contacts.", source: {} } });
  assert.ok(fixed.confidence >= 45); assert.equal(fixed.itemEquipment, "Fixed Camera");
  assert.ok(ptz.confidence >= 45); assert.equal(ptz.itemEquipment, "PTZ Camera");
  assert.ok(access.confidence >= 45); assert.equal(access.itemEquipment, "Access Control Door Assembly");
});
test("assembles a Task 8 profile from confirmed links only", () => { const requirement = { id: "r1", standards: [{ body: "NFPA", number: "72" }], attributes: [{ name: "Voltage", value: 24 }], manufacturers: [{ manufacturer: "Honeywell", status: "Approved" }] }; const profile = assembleKnowledgeProfile({ boqItem: { id: "b1", projectId: "p1" }, links: [{ requirementId: "r1", status: "Confirmed" }, { requirementId: "r2", status: "Suggested" }], requirements: [requirement, { id: "r2" }], conflicts: [], accessories: [], compatibility: [] }); assert.equal(profile.requirements.length, 1); assert.equal(profile.suggestedLinks.length, 1); assert.equal(profile.readiness.approvedForTask8, true); });
test("wires canonical persistence, publication, profiles and auditable applicability review", async () => { const [schema, worker, index] = await Promise.all([readFile(new URL("../db/schema.ts", import.meta.url), "utf8"), readFile(new URL("../worker/engineering-knowledge-api.mjs", import.meta.url), "utf8"), readFile(new URL("../worker/index.ts", import.meta.url), "utf8")]); for (const entity of ["engineeringFacts", "engineeringFactProvenance", "boqRequirementLinks", "engineeringRelationships", "engineeringKnowledgeDecisions", "engineeringKnowledgeConflicts", "engineeringTaxonomyTerms", "engineeringUnitDefinitions"]) assert.match(schema, new RegExp(`export const ${entity}`)); assert.match(worker, /approved_for_downstream=1/); assert.match(worker, /knowledge-profile/); assert.match(worker, /Requirement Applicability Reviewed/); assert.match(index, /handleEngineeringKnowledgeApi/); });
