import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { deriveEstimatorReadiness, deriveEstimatorRowReadiness } from "../app/domain/estimator-row-readiness.mjs";

const today = "2026-08-10";
const complete = { boqItemId: "boq_1", rowType: "BOQ Item", description: "Addressable smoke detector", normalizedDescription: "addressable smoke detector", numericQuantity: "10", normalizedUnit: "EA", system: "Fire Alarm", category: "Detector", candidateId: "candidate_1", productId: "product_1", candidateReviewStatus: "Selected", matchConfidence: 92, technicalApprovalStatus: "Approved", mandatoryFailures: "[]", safetyState: "Safe", technicalEligibility: "Eligible", pricingLineId: "line_1", priceRecordId: "price_1", unitCostMinor: 10000, sellingUnitMinor: 13000, sellingTotalMinor: 130000, currency: "SAR", priceApprovalStatus: "Approved", priceDownstreamUse: "Costing", priceValidUntil: "2026-12-31", understandingAvailable: false };

test("BOQ-only item enters estimator readiness without specification or requirement fields", () => { const result = deriveEstimatorRowReadiness(complete, { today }); assert.equal(result.status, "READY"); assert.equal(result.understanding.status, "Pending"); });
test("missing specification alone never produces MISSING", () => { const result = deriveEstimatorRowReadiness({ ...complete, understandingAvailable: true }, { today }); assert.equal(result.status, "READY"); assert.ok(!result.reasons.some((reason) => /specification/i.test(reason))); });
test("confirmed product and usable current price become READY", () => assert.equal(deriveEstimatorRowReadiness({ ...complete, understandingAvailable: true }, { today }).status, "READY"));
test("useful unconfirmed candidate becomes REVIEW", () => { const result = deriveEstimatorRowReadiness({ ...complete, candidateReviewStatus: "Needs Review", technicalApprovalStatus: null, understandingAvailable: true }, { today }); assert.equal(result.status, "REVIEW"); assert.match(result.reasons.join(" "), /engineer confirmation/i); });
test("missing quantity becomes MISSING", () => assert.equal(deriveEstimatorRowReadiness({ ...complete, numericQuantity: null }, { today }).status, "MISSING"));
test("no product evidence becomes MISSING", () => assert.equal(deriveEstimatorRowReadiness({ ...complete, candidateId: null, productId: null }, { today }).status, "MISSING"));
test("no usable price becomes MISSING", () => assert.equal(deriveEstimatorRowReadiness({ ...complete, priceRecordId: null, pricingLineId: null }, { today }).status, "MISSING"));
test("excluded BOQ items do not enter quotation coverage", () => { const result = deriveEstimatorReadiness([{ ...complete, understandingAvailable: true }, { ...complete, boqItemId: "boq_2", excludedScope: "Civil works" }], { today }); assert.deepEqual(result.summary, { total: 2, ready: 1, review: 0, missing: 0, excluded: 1, aiCoverage: 100, quotationCoverage: 100 }); });
test("project summary counts are server-derived correctly", () => { const result = deriveEstimatorReadiness([{ ...complete, boqItemId: "ready", understandingAvailable: true }, { ...complete, boqItemId: "review", candidateReviewStatus: "Needs Review", technicalApprovalStatus: null, understandingAvailable: true }, { ...complete, boqItemId: "missing", candidateId: null, productId: null }, { ...complete, boqItemId: "excluded", excludedScope: "By others" }], { today }); assert.deepEqual(result.summary, { total: 4, ready: 1, review: 1, missing: 1, excluded: 1, aiCoverage: 66.7, quotationCoverage: 33.3 }); });
test("endpoint is server-context scoped and enterprise workflow remains separate", () => { const api = fs.readFileSync(new URL("../worker/estimator-readiness-api.mjs", import.meta.url), "utf8"); const worker = fs.readFileSync(new URL("../worker/index.ts", import.meta.url), "utf8"); const enterprise = fs.readFileSync(new URL("../app/domain/presales-workflow-engine.mjs", import.meta.url), "utf8"); assert.match(api, /resolveApplicationContext/); assert.match(api, /p\.organization_id=\?/); assert.match(worker, /handleEstimatorReadinessApi/); assert.match(enterprise, /specificationExtractions/); assert.doesNotMatch(enterprise, /estimator-readiness-v1/); });
