import test from "node:test";
import assert from "node:assert/strict";
import { unzipSync, strFromU8 } from "fflate";
import { aggregateExportRows, buildDetailedRow, exportFilename, reconcileExport, safeExcelText, sheetsForMode, validateExportReadiness, visibleDetailedFields } from "../app/domain/excel-export-engine.mjs";
import { buildCostSheetXlsx } from "../worker/xlsx-cost-sheet.mjs";

const approvedRow = { quantity: 2, netUnitMaterialCost: 10, materialTotal: 20, accessoriesCost: 2, installationCost: 3, engineeringCost: 0, programmingCost: 0, testingCost: 1, otherDirectCost: 0, freight: 1, customs: 0, overheads: 1, risk: 1, contingency: 0, totalLineCost: 29, grossSellingUnitPrice: 20, customerDiscount: 1, netSellingTotal: 39, vat: 5.85, finalLineValue: 44.85, technicalStatus: "Technically Compliant", technicalApprovalStatus: "Approved", commercialApprovalStatus: "Approved", blockingConditions: "", pricingStatus: "Draft Price" };
test("formula injection is escaped without breaking negative numbers", () => { for (const value of ["=SUM(A1:A2)", "+cmd", "@external", "*unsafe", "-HYPERLINK()"]) assert.ok(safeExcelText(value).startsWith("'")); assert.equal(safeExcelText("-12.5"), "-12.5"); });
test("filename is sanitized and versioned", () => { const name = exportFilename({ projectName: "Riyadh / School", tenderNumber: "Q:12", revision: 3, date: new Date("2026-08-02T00:00:00Z") }); assert.equal(name, "AI-Pricing-Agent_Riyadh-School_Q-12_CostSheet_Rev03_2026-08-02.xlsx"); });
test("client-safe mode removes protected internal fields and sheets", () => { const fields = visibleDetailedFields("Client-Safe Export").map((x) => x.field); for (const field of ["supplierDiscount", "netUnitMaterialCost", "margin", "risk", "supplier"]) assert.ok(!fields.includes(field)); assert.ok(!sheetsForMode("Client-Safe Export").includes("Supplier and Price Sources")); });
test("missing quantity and price are not replaced by zero", () => { const row = buildDetailedRow({ boq: { sequence: 1, original_quantity: "", description: "Item" }, mode: "Draft Cost Sheet" }); assert.equal(row.quantity, null); assert.equal(row.netUnitMaterialCost, null); });
test("Honeywell material discount remains material scoped", () => { const row = buildDetailedRow({ boq: { sequence: 1, original_quantity: "2" }, pricing: { output: "{}", material_total_minor: 2000, total_cost_minor: 2500 }, discounts: [{ discount_type: "Manufacturer Discount", percentage_basis_points: 6500 }], components: [{ component_type: "Installation", amount_minor: 500 }], mode: "Commercial Review Cost Sheet" }); assert.equal(row.manufacturerDiscount, 0.65); assert.equal(row.installationCost, 5); assert.equal(row.materialTotal, 20); });
test("margin and markup remain distinct", () => { const row = buildDetailedRow({ boq: { sequence: 1, original_quantity: "1" }, pricing: { output: "{}", margin_basis_points: 2000, markup_basis_points: 2500 }, mode: "Commercial Review Cost Sheet" }); assert.equal(row.margin, 0.2); assert.equal(row.markup, 0.25); });
test("approved exports fail closed and draft exports show warnings", () => { assert.equal(validateExportReadiness({ mode: "Approved Cost Sheet", role: "Commercial Manager", rows: [approvedRow], reviewReadiness: "Exceptions Pending" }).permitted, false); const draft = validateExportReadiness({ mode: "Draft Cost Sheet", role: "Estimator", rows: [{ ...approvedRow, netUnitMaterialCost: null }], reviewReadiness: "Not Ready" }); assert.equal(draft.permitted, true); assert.ok(draft.warnings.some((x) => x.warning === "Missing Price")); });
test("totals and reconciliation use server-valued rows", () => { const totals = aggregateExportRows([approvedRow]); assert.equal(totals.totalCost, 29); assert.equal(totals.finalValue, 44.85); assert.equal(reconcileExport({ workbookTotals: totals, serverTotals: totals }).reconciled, true); assert.equal(reconcileExport({ workbookTotals: { ...totals, finalValue: 45 }, serverTotals: totals }).reconciled, false); });
test("generated workbook is a real multi-sheet OOXML package", () => { const totals = aggregateExportRows([approvedRow]), bytes = buildCostSheetXlsx({ mode: "Draft Cost Sheet", revision: 1, generatedAt: "2026-08-02", generatedBy: "user", project: { name: "Project", code: "P1", client: "Client", location: "Riyadh", currency: "SAR", scenario: "Base" }, rows: [{ ...approvedRow, lineNumber: 1, itemNumber: "1", description: "Smoke detector" }], totals, warningCount: 1, reviewReadiness: "Not Ready", reconciliation: { reconciled: true }, metadata: { exportId: "x1" }, alternatives: [], costComponents: [], priceSources: [], clarifications: [], reviews: [], assumptions: [] }), files = unzipSync(bytes); assert.ok(files["xl/workbook.xml"]); assert.match(strFromU8(files["xl/workbook.xml"]), /Detailed Cost Sheet/); assert.match(strFromU8(files["xl/worksheets/sheet1.xml"]), /DRAFT — NOT APPROVED/); });
