import test from "node:test";
import assert from "node:assert/strict";
import { aggregateProjectPricing, allocateSharedCost, applyDiscounts, calculatePricingLine, convertCurrency, priceValidity, sellingPrice, validateManualPriceInput } from "../app/domain/pricing-engine.mjs";

const at = "2026-08-02T00:00:00Z";
const base = { projectId: "p1", productId: "prod1", candidateId: "c1", selectedPriceSourceId: "src1", manufacturer: "Honeywell", quantity: 10, unit: "EA", projectCurrency: "SAR", calculatedAt: at, technicalApproval: { status: "Approved", candidateId: "c1" }, safetyDecision: { priceEligibility: "Eligible for Price Approval" }, priceSources: [{ id: "src1", productId: "prod1", projectId: "p1", amount: 100, currency: "SAR", priceType: "Supplier Quote", approvalStatus: "Approved", downstreamUse: "Costing Eligible", validUntil: "2026-12-31", reference: "Q-1" }], discounts: [], costComponents: [], sellingRule: { method: "Markup", rate: 25, minimumMargin: 10 }, customerDiscount: { percentage: 0 }, vatRule: { rate: 15 }, precision: 2 };

test("sequential discounts use the reducing balance", () => assert.deepEqual(applyDiscounts({ amount: 1000, discounts: [{ percentage: 50, order: 1, mode: "Sequential", scope: "Material", validUntil: "2027-01-01" }, { percentage: 10, order: 2, mode: "Sequential", scope: "Material", validUntil: "2027-01-01" }], context: { componentType: "Material", projectId: "p1", at, precision: 2 } }).net, 450));
test("additive discounts use the original base", () => assert.equal(applyDiscounts({ amount: 1000, discounts: [{ percentage: 50, order: 1, mode: "Additive", scope: "Material", validUntil: "2027-01-01" }, { percentage: 10, order: 2, mode: "Additive", scope: "Material", validUntil: "2027-01-01" }], context: { componentType: "Material", projectId: "p1", at, precision: 2 } }).net, 400));
test("Honeywell 65 percent discount is source and material scoped", () => { const discounts = [{ percentage: 65, order: 1, mode: "Sequential", scope: "Material", manufacturer: "Honeywell", sourceId: "hwl", validUntil: "2027-01-01" }]; assert.equal(applyDiscounts({ amount: 1000, discounts, context: { componentType: "Material", manufacturer: "Honeywell", sourceId: "hwl", projectId: "p1", at, precision: 2 } }).net, 350); assert.equal(applyDiscounts({ amount: 1000, discounts, context: { componentType: "Service", manufacturer: "Honeywell", sourceId: "hwl", projectId: "p1", at, precision: 2 } }).net, 1000); });
test("technically unapproved products are pricing blocked", () => assert.deepEqual(calculatePricingLine({ ...base, technicalApproval: null }).blockers, ["TECHNICAL_APPROVAL_REQUIRED"]));
test("expired sources cannot become selected", () => { const result = calculatePricingLine({ ...base, priceSources: [{ ...base.priceSources[0], validUntil: "2026-01-01" }] }); assert.equal(result.status, "Pricing Blocked"); assert.ok(result.blockers.includes("CURRENT_PRICE_SOURCE_REQUIRED")); });
test("project-specific sources do not cross project scope", () => assert.equal(calculatePricingLine({ ...base, projectId: "p2" }).status, "Pricing Blocked"));
test("price source is never selected silently", () => assert.ok(calculatePricingLine({ ...base, selectedPriceSourceId: null }).blockers.includes("PRICE_SOURCE_SELECTION_REQUIRED")));
test("currency conversion requires an approved current rate", () => assert.throws(() => convertCurrency({ amount: 100, sourceCurrency: "USD", projectCurrency: "SAR" }), { code: "EXCHANGE_RATE_REQUIRED" }));
test("currency conversion preserves original value", () => assert.deepEqual(convertCurrency({ amount: 100, sourceCurrency: "USD", projectCurrency: "SAR", exchangeRate: { from: "USD", to: "SAR", rate: 3.75, source: "Bank", version: 1, approvalStatus: "Approved", validUntil: "2027-01-01" } }).convertedAmount, 375));
test("margin and markup remain mathematically distinct", () => { const result = sellingPrice({ totalCost: 100, method: "Markup", rate: 25, minimumMargin: 0 }); assert.equal(result.markup, 25); assert.equal(result.margin, 20); });
test("negative and below-minimum margins are blocked", () => assert.throws(() => sellingPrice({ totalCost: 100, method: "Fixed", fixedPrice: 90, minimumMargin: 10 }), { code: "MINIMUM_MARGIN_BREACH" }));
test("customer discount cannot silently breach minimum margin", () => assert.equal(calculatePricingLine({ ...base, customerDiscount: { percentage: 20 } }).blockers[0], "CUSTOMER_DISCOUNT_MINIMUM_BREACH"));
test("VAT uses the project rule", () => { const result = calculatePricingLine(base); assert.equal(result.netSelling, 1250); assert.equal(result.vat, 187.5); assert.equal(result.finalValue, 1437.5); });
test("blank quantity is never treated as zero", () => assert.ok(calculatePricingLine({ ...base, quantity: "" }).blockers.includes("QUANTITY_REQUIRED")));
test("shared costs reconcile without double counting rounding residue", () => { const allocation = allocateSharedCost({ amount: 100, items: [{ id: 1 }, { id: 2 }, { id: 3 }], method: "Even" }); assert.equal(allocation.reduce((sum, entry) => sum + entry.amount, 0), 100); });
test("manual pricing requires source, reason, scope, role and technical approval", () => assert.equal(validateManualPriceInput({ input: { projectId: "p", boqItemId: "b", candidateId: "c", productId: "x", price: 10, currency: "SAR", source: "Q1", validUntil: "2027-01-01", reason: "Urgent quote", scope: "This item" }, user: { role: "Procurement" }, technicalApproval: { status: "Approved", candidateId: "c" } }).permitted, true));
test("project aggregation uses only approval-ready pricing lines", () => { const line = calculatePricingLine(base), summary = aggregateProjectPricing([line, { approvalReady: false, totalCost: 999 }]); assert.equal(summary.pricedItemCount, 1); assert.equal(summary.totalCost, 1000); });
test("validity states distinguish expired and missing", () => { assert.equal(priceValidity({ validUntil: null }, at), "No Validity Provided"); assert.equal(priceValidity({ validUntil: "2026-01-01" }, at), "Expired"); });
