import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { DatabaseSync } from "node:sqlite";
import { classifyProductSourceValidity, normalizeManufacturerName, PRODUCT_IDENTITY_REVIEW_OVERLAY_SQL, promoteProductIdentity, reviewProductIdentity } from "../worker/product-identity-api.mjs";

const d1=raw=>({prepare(sql){const op=(values=[])=>({first:async()=>raw.prepare(sql).get(...values)||null,all:async()=>({results:raw.prepare(sql).all(...values)}),run:async()=>{const result=raw.prepare(sql).run(...values);return {meta:{changes:Number(result.changes)}};}});return {...op(),bind:(...values)=>op(values)};},async batch(statements){raw.exec("BEGIN IMMEDIATE");try{const output=[];for(const statement of statements)output.push(await statement.run());raw.exec("COMMIT");return output;}catch(error){raw.exec("ROLLBACK");throw error;}}});
const schema=`
PRAGMA foreign_keys=ON;
CREATE TABLE organizations(id TEXT PRIMARY KEY);
CREATE TABLE product_identities(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,identity_key TEXT,manufacturer TEXT,unit TEXT,review_status TEXT,version INTEGER,official_product_code TEXT,normalized_product_code TEXT,description TEXT,superseded_at TEXT,updated_at TEXT);
CREATE TABLE product_identity_events(id TEXT PRIMARY KEY,organization_id TEXT,product_identity_id TEXT,run_id TEXT,event_type TEXT,details TEXT,actor_user_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE product_manufacturers(id TEXT PRIMARY KEY,name TEXT,normalized_name TEXT UNIQUE,status TEXT,created_by TEXT);
CREATE TABLE library_products(id TEXT PRIMARY KEY,manufacturer_id TEXT,part_number TEXT,normalized_part_number TEXT,description TEXT,lifecycle_status TEXT,attributes TEXT,standards TEXT,review_status TEXT,approved_for_discovery INTEGER,created_by TEXT,identity_status TEXT,library_scope TEXT,organization_id TEXT,library_project_id TEXT,UNIQUE(manufacturer_id,normalized_part_number));
CREATE TABLE documents(id TEXT PRIMARY KEY,project_id TEXT);
CREATE TABLE document_versions(id TEXT PRIMARY KEY,document_id TEXT,file_name TEXT,sha256 TEXT);
CREATE TABLE product_sources(id TEXT PRIMARY KEY,project_id TEXT,document_id TEXT,document_version_id TEXT,checksum TEXT,source_type TEXT,authority TEXT,scope_type TEXT,file_name TEXT,release_version TEXT,effective_from TEXT,valid_until TEXT,currency TEXT,validity_state TEXT,review_status TEXT,downstream_use TEXT,metadata TEXT,created_by TEXT,organization_id TEXT);
CREATE TABLE product_source_evidence(id TEXT PRIMARY KEY,product_id TEXT,source_id TEXT,sheet TEXT,row_number INTEGER,page INTEGER,cells TEXT,original_text TEXT,parser_version TEXT,UNIQUE(product_id,source_id,sheet,row_number));
CREATE TABLE knowledge_files(id TEXT PRIMARY KEY,organization_id TEXT,file_name TEXT,sha256 TEXT,summary TEXT,detected_type TEXT);
CREATE TABLE knowledge_facts(id TEXT PRIMARY KEY,knowledge_file_id TEXT);
CREATE TABLE product_identity_observations(id TEXT PRIMARY KEY,organization_id TEXT,product_identity_id TEXT,knowledge_file_id TEXT,knowledge_fact_id TEXT,original_value TEXT,attributes TEXT,source_location TEXT,created_at TEXT);
CREATE TABLE knowledge_product_links(id TEXT PRIMARY KEY,organization_id TEXT,knowledge_fact_id TEXT,part_number TEXT,existing_product_id TEXT,link_state TEXT,new_information TEXT);
CREATE TABLE product_library_decisions(id TEXT PRIMARY KEY,project_id TEXT,entity_type TEXT,entity_id TEXT,action TEXT,previous_value TEXT,new_value TEXT,reason TEXT,decided_by TEXT,decided_role TEXT);
CREATE TABLE price_records(id TEXT PRIMARY KEY,costing_eligible INTEGER);
CREATE TABLE pricing_lines(id TEXT PRIMARY KEY);
`;
const migration=await readFile(new URL("../drizzle/0056_product_identity_review_promotion.sql",import.meta.url),"utf8");
const fixture=({manufacturer=null,unit=null,superseded=false,withProvenance=true}={})=>{const raw=new DatabaseSync(":memory:");raw.exec(schema);raw.exec(migration);raw.prepare("INSERT INTO organizations VALUES (?)").run("org-a");raw.prepare("INSERT INTO organizations VALUES (?)").run("org-b");raw.prepare("INSERT INTO product_identities VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").run("identity-a","org-a","key",manufacturer,unit,"Needs Review",1,"PART-100","PART100","CAT 6A cable",superseded?"2026-01-01":null,"now");if(withProvenance){const location={documentId:"document-a",documentVersionId:"version-a",checksum:"sha-real",sheet:"Quote",page:2,row:17,parser:"supplier-pdf",parserVersion:"2.4"},attributes={supplier:"Real Supplier",quotationReference:"Q-101",issueDate:"2025-01-01",validUntil:"2025-02-01",sourceType:"Supplier Quotation",historicalObservation:true,currency:"SAR",priceType:"Supplier Quotation Price",costingEligible:false};raw.exec("INSERT INTO documents VALUES ('document-a','project-a'); INSERT INTO document_versions VALUES ('version-a','document-a','quote-real.pdf','sha-real'); INSERT INTO knowledge_files VALUES ('file-a','org-a','quote-real.pdf','sha-real','{}','Supplier Quotation'); INSERT INTO knowledge_facts VALUES ('fact-a','file-a'); INSERT INTO knowledge_facts VALUES ('fact-b','file-a');");raw.prepare("INSERT INTO product_identity_observations VALUES (?,?,?,?,?,?,?,?,?)").run("obs-a","org-a","identity-a","file-a","fact-a","PART-100",JSON.stringify(attributes),JSON.stringify(location),"now");raw.prepare("INSERT INTO product_identity_observations VALUES (?,?,?,?,?,?,?,?,?)").run("obs-b","org-a","identity-a","file-a","fact-b","CAT 6A cable",JSON.stringify(attributes),JSON.stringify({...location,row:18}),"now");raw.prepare("INSERT INTO knowledge_product_links VALUES (?,?,?,?,?,?,?)").run("link-a","org-a","fact-a","PART-100",null,"New Product Candidate",JSON.stringify({originalField:"preserved",nested:{value:7}}));}return {raw,DB:d1(raw)};};
const actor=(permission="Library Manager")=>({id:"user-a",permission,role:permission});
const req=(operation,body)=>new Request(`http://local/api/product-identities/identity-a/${operation}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
const reviewBody=(overrides={})=>({manufacturer:"Johnson Controls",unit:"RL",reason:"Verified against explicit supplier quotation evidence.",evidence:{facts:["fact-a"]},idempotencyKey:"review-key",expectedVersion:1,...overrides});
const promoteBody=(overrides={})=>({reason:"Promote reviewed identity as additive organization knowledge.",idempotencyKey:"promote-key",expectedVersion:2,...overrides});
const performReview=(DB,overrides={})=>reviewProductIdentity(req("review",reviewBody(overrides)),{DB},actor("Library Reviewer"),{id:"org-a"},"identity-a");
const performReviewBody=(DB,body,identityId="identity-a")=>reviewProductIdentity(req("review",body),{DB},actor("Library Reviewer"),{id:"org-a"},identityId);
const performPromotion=(DB,overrides={},user=actor())=>promoteProductIdentity(req("promote",promoteBody(overrides)),{DB},user,{id:"org-a"},"identity-a");

test("review is atomic, idempotent, preserves raw observations and supports explicit NULL overrides",async()=>{const {raw,DB}=fixture();assert.equal((await performReview(DB,{manufacturer:null,unit:"RL"})).status,201);assert.equal(raw.prepare("SELECT manufacturer FROM product_identities").get().manufacturer,null);assert.equal(raw.prepare("SELECT manufacturer_reviewed FROM product_identity_reviews").get().manufacturer_reviewed,1);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_observations").get().count,2);assert.equal((await performReview(DB,{manufacturer:null,unit:"RL"})).status,200);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_reviews").get().count,1);raw.close();});

test("review idempotency is route-bound and never leaks another identity's review",async()=>{const {raw,DB}=fixture();assert.equal((await performReview(DB)).status,201);const replay=await performReview(DB),replayBody=await replay.json();assert.equal(replay.status,200);assert.equal(replayBody.review.product_identity_id,"identity-a");const conflict=await performReviewBody(DB,reviewBody(),"identity-b"),conflictBody=await conflict.json();assert.equal(conflict.status,409);assert.equal(conflictBody.error.code,"IDEMPOTENCY_KEY_CONFLICT");assert.equal(Object.hasOwn(conflictBody,"review"),false);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_reviews").get().count,1);raw.close();});

test("sequential reviews retain cumulative human resolution and immutable field-level audit proof",async()=>{const {raw,DB}=fixture();const observationsBefore=raw.prepare("SELECT * FROM product_identity_observations ORDER BY id").all();const first={manufacturer:"Johnson Controls",reason:"Manufacturer verified from the cited supplier evidence.",evidence:{facts:["fact-a"]},idempotencyKey:"manufacturer-review",expectedVersion:1};assert.equal((await performReviewBody(DB,first)).status,201);const second={unit:"RL",reason:"Unit verified from the cited supplier evidence row.",evidence:{facts:["fact-b"]},idempotencyKey:"unit-review",expectedVersion:2};assert.equal((await performReviewBody(DB,second)).status,201);const reviews=raw.prepare("SELECT * FROM product_identity_reviews ORDER BY identity_version_after").all();assert.deepEqual(reviews.map(row=>row.status),["Superseded","Active"]);assert.equal(reviews[0].manufacturer_reviewed,1);assert.equal(reviews[0].unit_reviewed,0);assert.equal(reviews[1].manufacturer_reviewed,1);assert.equal(reviews[1].unit_reviewed,1);assert.equal(reviews[1].resolved_manufacturer,"Johnson Controls");assert.equal(reviews[1].resolved_unit,"RL");raw.exec("UPDATE product_identities SET manufacturer='Automatic Wrong',unit='PCS'");raw.prepare(PRODUCT_IDENTITY_REVIEW_OVERLAY_SQL).run("org-a");const rematerialized=raw.prepare("SELECT manufacturer,unit FROM product_identities").get();assert.equal(rematerialized.manufacturer,"Johnson Controls");assert.equal(rematerialized.unit,"RL");assert.deepEqual(raw.prepare("SELECT * FROM product_identity_observations ORDER BY id").all(),observationsBefore);assert.equal((await performPromotion(DB,{expectedVersion:3})).status,201);const events=raw.prepare("SELECT details FROM product_identity_events WHERE event_type='Product Identity Reviewed' ORDER BY created_at,CAST(json_extract(details,'$.new.version') AS INTEGER),id").all().map(row=>JSON.parse(row.details));assert.equal(events[0].submittedReviewedFields.manufacturer,true);assert.equal(events[1].submittedReviewedFields.manufacturer,false);assert.equal(events[1].cumulativeReviewedFields.manufacturer,true);assert.ok(events[1].carriedFromReviewId);raw.close();});

test("rematerialization applies explicitly reviewed NULL and retains unreviewed automatic fields",async()=>{const {raw,DB}=fixture();await performReview(DB,{manufacturer:null,unit:"RL"});raw.exec("UPDATE product_identities SET manufacturer='Automatic Wrong',unit='PCS'");raw.prepare(PRODUCT_IDENTITY_REVIEW_OVERLAY_SQL).run("org-a");const identity=raw.prepare("SELECT manufacturer,unit FROM product_identities").get();assert.equal(identity.manufacturer,null);assert.equal(identity.unit,"RL");raw.close();});

test("stale review leaves identity, old review and audit state completely unchanged",async()=>{const {raw,DB}=fixture();await performReview(DB);const before={identity:raw.prepare("SELECT * FROM product_identities").get(),reviews:raw.prepare("SELECT * FROM product_identity_reviews").all(),events:raw.prepare("SELECT * FROM product_identity_events").all()};const response=await reviewProductIdentity(req("review",reviewBody({idempotencyKey:"stale-key",expectedVersion:1})),{DB},actor("Library Reviewer"),{id:"org-a"},"identity-a");assert.equal(response.status,409);assert.deepEqual(raw.prepare("SELECT * FROM product_identities").get(),before.identity);assert.deepEqual(raw.prepare("SELECT * FROM product_identity_reviews").all(),before.reviews);assert.deepEqual(raw.prepare("SELECT * FROM product_identity_events").all(),before.events);raw.close();});

test("compare-and-swap guard rejects a version change between read and mutation with zero review/audit writes",async()=>{const {raw,DB}=fixture(),racingDB={...DB,async batch(statements){raw.exec("UPDATE product_identities SET version=2 WHERE id='identity-a'");return DB.batch(statements);}};const response=await reviewProductIdentity(req("review",reviewBody()),{DB:racingDB},actor("Library Reviewer"),{id:"org-a"},"identity-a");assert.equal(response.status,409);assert.equal(raw.prepare("SELECT version FROM product_identities").get().version,2);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_review_guards").get().count,0);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_reviews").get().count,0);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_events").get().count,0);raw.close();});

test("promotion gates permission, completeness, scope, supersession and stale versions",async()=>{for(const [options,expected] of [[{manufacturer:null,unit:"RL"},422],[{manufacturer:"Maker",unit:null},422],[{manufacturer:"Maker",unit:"EA",superseded:true},409]]){const {raw,DB}=fixture(options);if(!options.superseded)await performReview(DB,{manufacturer:options.manufacturer,unit:options.unit});assert.equal((await performPromotion(DB,{expectedVersion:options.superseded?1:2})).status,expected);raw.close();}const {raw,DB}=fixture();await performReview(DB);assert.equal((await performPromotion(DB,{},actor("Library Reviewer"))).status,403);assert.equal((await promoteProductIdentity(req("promote",promoteBody()),{DB},actor(),{id:"org-b"},"identity-a")).status,404);assert.equal((await performPromotion(DB,{expectedVersion:99})).status,409);raw.close();});

test("promotion fails closed without complete verified source provenance",async()=>{const {raw,DB}=fixture({withProvenance:false});await performReview(DB);const response=await performPromotion(DB);assert.equal(response.status,422);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_promotions").get().count,0);assert.equal(raw.prepare("SELECT count(*) count FROM product_sources").get().count,0);raw.close();});

test("functional promotion creates only governed discovery records and preserves all provenance and learning",async()=>{const {raw,DB}=fixture();await performReview(DB);const response=await performPromotion(DB),body=await response.json();assert.equal(response.status,201);const manufacturer=raw.prepare("SELECT * FROM product_manufacturers").get(),product=raw.prepare("SELECT * FROM library_products").get(),source=raw.prepare("SELECT * FROM product_sources").get(),evidence=raw.prepare("SELECT * FROM product_source_evidence ORDER BY row_number").all(),link=raw.prepare("SELECT * FROM knowledge_product_links").get(),promotion=raw.prepare("SELECT * FROM product_identity_promotions").get();assert.equal(manufacturer.status,"Needs Review");assert.equal(manufacturer.normalized_name,"JOHNSON CONTROLS");assert.equal(product.library_scope,"Organization Library");assert.equal(product.organization_id,"org-a");assert.equal(product.approved_for_discovery,0);assert.equal(product.review_status,"Needs Review");assert.equal(product.lifecycle_status,"Unknown — Review Required");assert.equal(JSON.parse(product.attributes)[0].value,"RL");assert.equal(source.document_id,"document-a");assert.equal(source.document_version_id,"version-a");assert.equal(source.checksum,"sha-real");assert.equal(source.authority,"Supplier");assert.equal(source.downstream_use,"Discovery Only");assert.equal(source.validity_state,"Historical / Expired");assert.equal(evidence.length,2);assert.deepEqual(evidence.map(row=>[row.page,row.row_number,row.parser_version]),[[2,17,"supplier-pdf:2.4"],[2,18,"supplier-pdf:2.4"]]);assert.equal(JSON.parse(link.new_information).originalField,"preserved");assert.equal(JSON.parse(link.new_information).nested.value,7);assert.equal(JSON.parse(link.new_information).promotion.identityId,"identity-a");assert.equal(promotion.linked_knowledge_count,1);assert.equal(body.linkedKnowledgeCount,1);assert.equal(raw.prepare("SELECT count(*) count FROM price_records").get().count,0);assert.equal(raw.prepare("SELECT count(*) count FROM pricing_lines").get().count,0);raw.close();});

test("manufacturer normalization reuses safe punctuation/capitalization variants",async()=>{assert.equal(normalizeManufacturerName("  Johnson,   Controls "),"JOHNSON CONTROLS");const {raw,DB}=fixture();raw.exec("INSERT INTO product_manufacturers VALUES ('manufacturer-existing','Johnson Controls','JOHNSON CONTROLS','Reviewed','admin')");await performReview(DB,{manufacturer:"johnson, controls"});assert.equal((await performPromotion(DB)).status,201);assert.equal(raw.prepare("SELECT count(*) count FROM product_manufacturers").get().count,1);assert.equal(raw.prepare("SELECT manufacturer_id FROM library_products").get().manufacturer_id,"manufacturer-existing");raw.close();});

test("promotion replay creates no duplicate product, source, evidence, events or decisions",async()=>{const {raw,DB}=fixture();await performReview(DB);assert.equal((await performPromotion(DB)).status,201);assert.equal((await performPromotion(DB)).status,200);for(const [table,count] of [["library_products",1],["product_sources",1],["product_source_evidence",2],["product_identity_promotions",1],["product_library_decisions",1]])assert.equal(raw.prepare(`SELECT count(*) count FROM ${table}`).get().count,count);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_events WHERE event_type='Canonical Product Promoted'").get().count,1);raw.close();});

test("promotion idempotency is route-bound and distinguishes replay from an already-promoted identity",async()=>{const {raw,DB}=fixture();await performReview(DB);assert.equal((await performPromotion(DB)).status,201);const same=await performPromotion(DB),sameBody=await same.json();assert.equal(same.status,200);assert.equal(sameBody.replayKind,"Same Request Replay");assert.equal(sameBody.promotion.product_identity_id,"identity-a");const newKey=await performPromotion(DB,{idempotencyKey:"new-promotion-key"}),newKeyBody=await newKey.json();assert.equal(newKey.status,200);assert.equal(newKeyBody.replayKind,"Identity Already Promoted");const conflict=await promoteProductIdentity(req("promote",promoteBody()),{DB},actor(),{id:"org-a"},"identity-b"),conflictBody=await conflict.json();assert.equal(conflict.status,409);assert.equal(conflictBody.error.code,"IDEMPOTENCY_KEY_CONFLICT");assert.equal(Object.hasOwn(conflictBody,"promotion"),false);assert.equal(raw.prepare("SELECT count(*) count FROM product_identity_promotions").get().count,1);raw.close();});

test("historical validity states distinguish expiry, future validity and unknown validity deterministically",()=>{assert.equal(classifyProductSourceValidity({historicalObservation:true,validUntil:"2025-12-31",currentDate:"2026-01-01"}),"Historical / Expired");assert.equal(classifyProductSourceValidity({historicalObservation:true,validUntil:"2027-12-31",currentDate:"2026-01-01"}),"Historical / Validity Review Required");assert.equal(classifyProductSourceValidity({historicalObservation:true,validUntil:null,currentDate:"2026-01-01"}),"Validity Review Required");assert.equal(classifyProductSourceValidity({historicalObservation:false,validUntil:null,currentDate:"2026-01-01"}),"Validity Review Required");});

test("existing current-organization product is reused while global and foreign scopes fail closed",async()=>{for(const [scope,owner,expected] of [["Organization Library","org-a",201],["Organization Library","org-b",409],["Global Library",null,409],["Project Library","org-a",409]]){const {raw,DB}=fixture();raw.exec("INSERT INTO product_manufacturers VALUES ('m-existing','Johnson Controls','JOHNSON CONTROLS','Reviewed','admin')");raw.prepare("INSERT INTO library_products VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run("p-existing","m-existing","PART-100","PART100","Existing","Unknown — Review Required","[]","[]","Needs Review",0,"admin","Active",scope,owner,scope==='Project Library'?"project-x":null);await performReview(DB);assert.equal((await performPromotion(DB)).status,expected);if(expected===201)assert.equal(raw.prepare("SELECT count(*) count FROM library_products").get().count,1);raw.close();}});

test("implementation contains no pilot-specific provenance constants and materialization preserves reviewed NULL",async()=>{const api=await readFile(new URL("../worker/product-identity-api.mjs",import.meta.url),"utf8");for(const forbidden of ["UU004891568","Bab Al Khair","Sahabeh Shabkat","project_8783827a","doc_55ce735f","ver_852f4db3","6cd29fc2","SO26-06-15-02"])assert.equal(api.includes(forbidden),false);assert.match(api,/manufacturer_reviewed/);assert.match(api,/unit_reviewed/);assert.match(api,/automaticSourceBlockers/);assert.doesNotMatch(api,/INSERT INTO (price_records|pricing_lines)/);});
