import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { eligiblePrices, ingestHoneywellFarenhytWorkbook, searchProductLibrary } from "../app/domain/product-price-library.mjs";

const workbookPath = "/Users/serein-b/Downloads/KSA Honeywell Farenhyt Series Price List -2023.xlsx";
test("ingests the supplied Honeywell workbook with real source provenance", async () => { const result = ingestHoneywellFarenhytWorkbook(new Uint8Array(await readFile(workbookPath)), { fileName: workbookPath, documentId: "doc-price" }); assert.equal(result.summary.productsDetected, 504); assert.equal(result.summary.pricesDetected, 504); assert.equal(result.priceSource.currency, "USD"); assert.equal(result.priceSource.releaseVersion, "V23.1"); assert.match(result.priceSource.effectiveFrom, /March 2023/i); assert.equal(result.products[0].source.sheet, "2023 Farenhyt"); assert.ok(result.products[0].source.row > 0); });
test("excludes scratch formulas and retains lifecycle evidence separately", async () => { const result = ingestHoneywellFarenhytWorkbook(new Uint8Array(await readFile(workbookPath))); assert.ok(result.excludedSheets.some((sheet) => sheet.name === "Sheet1")); assert.equal(result.summary.lifecycleRecords, 82); assert.ok(result.lifecycle.some((record) => record.lifecycleStatus === "Discontinued — No Replacement")); });
test("keeps historical prices discovery-only and ineligible for costing", async () => { const result = ingestHoneywellFarenhytWorkbook(new Uint8Array(await readFile(workbookPath))); assert.equal(result.summary.validCurrentPrices, 0); assert.equal(eligiblePrices(result.prices).length, 0); assert.ok(result.prices.every((price) => price.downstreamUse === "Discovery Only")); });
test("supports exact and partial structured product search without BOQ ranking", async () => { const result = ingestHoneywellFarenhytWorkbook(new Uint8Array(await readFile(workbookPath))); const exact = searchProductLibrary(result.products, "IFP-2100HV"); const partial = searchProductLibrary(result.products, "smoke detector", { manufacturer: "Honeywell" }); assert.ok(exact.some((product) => product.partNumber === "IFP-2100HV")); assert.ok(partial.length > 0); assert.ok(partial.every((product) => product.manufacturer === "Honeywell")); });
