import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { handleReviewWorkflowApi } from "../worker/review-workflow-api.mjs";
const root = new URL("../", import.meta.url);
test("review API fails closed without configured application context", async () => { const response = await handleReviewWorkflowApi(new Request("https://local.test/api/reviews/projects/p1/queue"), { DB: {} }); assert.equal(response.status, 503); assert.equal((await response.json()).error.code, "APPLICATION_CONTEXT_UNAVAILABLE"); });
test("Task 13 persists complete review entities", async () => { const schema = await readFile(new URL("db/schema.ts", root), "utf8"); for (const entity of ["reviewQueueItems", "reviewAssignments", "reviewDecisions", "reviewApprovalSteps", "reviewApprovalConditions", "reviewDependencies", "reviewClarifications", "reviewConflictResolutions", "reviewComments", "reviewAttachments", "reviewNotifications", "reviewAuditLog"]) assert.match(schema, new RegExp(`export const ${entity}`)); });
test("review controls are server enforced", async () => { const api = await readFile(new URL("worker/review-workflow-api.mjs", root), "utf8"), domain = await readFile(new URL("app/domain/review-workflow.mjs", root), "utf8"); for (const control of ["project_members", "STALE_REVIEW_VERSION", "INVALID_BULK_ACTION", "review_audit_log", "calculateQuotationReadiness", "validateDecision"]) assert.match(api, new RegExp(control)); for (const control of ["SAFETY_APPROVAL_BLOCKED", "TECHNICAL_APPROVAL_REQUIRED", "PRICING_APPROVAL_BLOCKED"]) assert.match(domain, new RegExp(control)); assert.doesNotMatch(api, /localStorage|sessionStorage|x-user-role/); });
test("review API routes before pricing", async () => { const worker = await readFile(new URL("worker/index.ts", root), "utf8"), review = worker.indexOf("handleReviewWorkflowApi(request, env)"), pricing = worker.indexOf("handlePricingApi(request, env)"), framework = worker.indexOf("handler.fetch(request, env, ctx)"); assert.ok(review > 0 && review < pricing && pricing < framework); });
