import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";
const engine=await readFile("app/domain/symbol-cell-segmentation-engine.mjs","utf8"),api=await readFile("worker/symbol-cell-segmentation-api.mjs","utf8"),ui=await readFile("app/page.tsx","utf8"),symbol=await readFile("worker/drawing-symbol-recognition-api.mjs","utf8");
test("clusters by bounded connectivity and style without largest-cluster selection",()=>{assert.match(engine,/gap\(a\.boundingBox, b\.boundingBox\)/);assert.match(engine,/stroke/);assert.match(engine,/fill/);assert.match(engine,/transform/);assert.doesNotMatch(engine,/largest/i)});
test("excludes cross-boundary borders micro-fragments text outlines and hatching",()=>{for(const term of["Crosses approved symbol-cell boundary","Table border or leader","Background micro-fragment","Likely text outlines or hatching"])assert.match(engine,new RegExp(term))});
test("preserves original fragments membership boxes signatures and reasons",()=>{for(const term of["original_fragments","fragment_count","geometry_signature","detection_basis","exclusion_reason"])assert.match(api,new RegExp(term))});
test("supports governed cluster review and immutable events",()=>{for(const term of["confirm","reject","add-fragments","remove-fragments","merge-clusters","split-cluster","restore"])assert.match(api,new RegExp(term));assert.match(api,/drawing_symbol_cluster_events/)});
test("publishes only approved clusters with full blocked-row count",()=>{assert.match(api,/review_status='Approved'/);assert.match(api,/approved_row_count/);assert.match(api,/drawing_legend_geometry_approved_links/)});
test("recognition consumes approved cluster geometry only",()=>{assert.match(symbol,/drawing_legend_geometry_approved_links/);assert.match(symbol,/approved_geometry_signature/)});
test("workspace deep links and downstream mutation boundaries remain intact",()=>{assert.match(ui,/Symbol Cell Segmentation/);assert.match(ui,/symbolSegmentation/);for(const forbidden of[/INSERT INTO engineering_objects/i,/INSERT INTO product_match/i,/INSERT INTO pricing_/i])assert.doesNotMatch(api,forbidden)});
