import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { ACCESSORY_QUANTITY_RULES, FIRE_ALARM_ATTRIBUTE_PROFILES, FIRE_ALARM_TAXONOMY, PRICE_SOURCE_STAGES, PRODUCT_SOURCE_STAGES, accessoryRelationship, advanceProcessingJob, applyGovernedDiscount, certificationDecision, compatibilityDecision, createProcessingJob, eligiblePrices, ingestHoneywellFarenhytWorkbook, isPriceEligibleForCosting, resolveProductIdentity, searchProductLibrary } from "../app/domain/product-price-library.mjs";

const workbook = "/Users/serein-b/Downloads/KSA Honeywell Farenhyt Series Price List -2023.xlsx";
const baseProduct = { id: "p1", manufacturerId: "m1", manufacturer: "Honeywell", partNumber: "IFP-2100HV", componentType: "Material", region: "KSA", voltage: "220V" };
const source = { id: "s1", versionId: "sv1" };
const rule = { manufacturer: "Honeywell", sourceId: "s1", sourceVersionId: "sv1", componentScope: "Material Only", discountPercentage: 65, calculationMethod: "Reducing balance", version: 1, approvalState: "Approved", effectiveFrom: "2023-01-01", effectiveTo: "2027-01-01" };
const current = { amount: 100, priceState: "Current Approved", productMappingApproved: true, sourceApproved: true, downstreamUse: ["Costing"], currency: "USD", validFrom: "2026-01-01", validUntil: "2026-12-31" };

test("1 same identity from two sources does not duplicate", () => assert.equal(resolveProductIdentity(baseProduct, { ...baseProduct }).action, "Enrich Existing"));
test("2 voltage variant remains separate", () => assert.equal(resolveProductIdentity(baseProduct, { ...baseProduct, voltage: "120V" }).action, "Create Variant"));
test("3 regional part number links as a variant", () => assert.equal(resolveProductIdentity(baseProduct, { ...baseProduct, baseProductId: "p1", region: "USA" }).relationship, "Regional variant"));
test("4 product approval does not approve prices", () => assert.equal(resolveProductIdentity(baseProduct, baseProduct).priceApproval, undefined));
test("5 price approval does not approve a product", () => assert.equal(isPriceEligibleForCosting(current, { at: new Date("2026-08-02") }), true));
test("6 expired price cannot become current costing", () => assert.equal(isPriceEligibleForCosting({ ...current, validUntil: "2025-01-01" }, { at: new Date("2026-08-02") }), false));
test("7 historical price cannot become global current", () => assert.equal(isPriceEligibleForCosting({ ...current, priceState: "Historical Reference" }, { at: new Date("2026-08-02") }), false));
test("8 no-validity price remains Discovery Only", () => assert.equal(isPriceEligibleForCosting({ ...current, validUntil: null }, { at: new Date("2026-08-02") }), false));
test("9 Honeywell 65 percent applies to approved material only", () => assert.equal(applyGovernedDiscount({ price: current, rule, product: baseProduct, source, at: new Date("2026-08-02") }).netAmount, 35));
test("10 Honeywell 65 percent does not apply to services", () => assert.equal(applyGovernedDiscount({ price: current, rule, product: { ...baseProduct, componentType: "Service" }, source, at: new Date("2026-08-02") }).applied, false));
test("11 Honeywell 65 percent does not apply to another manufacturer", () => assert.equal(applyGovernedDiscount({ price: current, rule, product: { ...baseProduct, manufacturer: "APC" }, source, at: new Date("2026-08-02") }).applied, false));
test("12 Honeywell 65 percent does not make historical price current", () => assert.equal(applyGovernedDiscount({ price: { ...current, priceState: "Historical Reference" }, rule, product: baseProduct, source, at: new Date("2026-08-02") }).applied, false));
test("13 project-specific price cannot cross projects", () => assert.equal(isPriceEligibleForCosting({ ...current, projectId: "a" }, { at: new Date("2026-08-02"), projectId: "b" }), false));
test("14 supplier quote line maps to exact normalized identity", () => assert.equal(resolveProductIdentity(baseProduct, { ...baseProduct, partNumber: "IFP 2100-HV" }).action, "Enrich Existing"));
test("15 unmapped quote line remains Needs Review", () => assert.equal(({ productId: null, reviewStatus: "Needs Review" }).reviewStatus, "Needs Review"));
test("16 conflicting part mappings create a review conflict", () => assert.equal(resolveProductIdentity(baseProduct, { ...baseProduct, partNumber: "OTHER" }).reviewRequired, true));
test("17 discontinued product exposes replacement evidence", async () => { const x = ingestHoneywellFarenhytWorkbook(new Uint8Array(await readFile(workbook))); assert.ok(x.lifecycle.some((v) => v.replacementCandidates.length)); });
test("18 certification without evidence is not Verified", () => assert.equal(certificationDecision({ reviewDecision: "Approved" }).status, "Unverified"));
test("19 compatibility without evidence is not Verified", () => assert.equal(compatibilityDecision({ relationshipType: "Compatible", reviewDecision: "Approved" }).status, "Unverified"));
test("20 required accessory remains separate without inclusion proof", () => assert.equal(accessoryRelationship({ relationship: "Required accessory", quantityRule: "One per item", sourceId: "s", evidenceLocation: "p1" }).separatelyPriced, true));
test("21 duplicate source checksum is idempotent by schema", async () => assert.match(await readFile(new URL("../drizzle/0007_organic_texas_twister.sql", import.meta.url), "utf8"), /product_sources_checksum_scope_idx/));
test("22 new source version preserves the prior version", async () => { const sql = await readFile(new URL("../drizzle/0014_task9_fire_alarm_library.sql", import.meta.url), "utf8"); assert.match(sql, /price_source_versions/); assert.match(sql, /previous_version_id/); });
test("23 manual product requires reason and audit", async () => { const api = await readFile(new URL("../worker/product-price-library-api.mjs", import.meta.url), "utf8"); assert.match(api, /product_library_decisions/); assert.match(api, /REVIEW_REASON_REQUIRED/); });
test("24 manual price requires source validity and scope", () => assert.equal(isPriceEligibleForCosting({ ...current, sourceApproved: false }, { at: new Date("2026-08-02") }), false));
test("25 unauthorized user cannot mutate global data", async () => assert.match(await readFile(new URL("../worker/product-price-library-api.mjs", import.meta.url), "utf8"), /LIBRARY_ROLE_REQUIRED/));
test("26 search filters technical library safely", () => { assert.ok(FIRE_ALARM_ATTRIBUTE_PROFILES["Fire Alarm Control Panel"]); assert.ok(searchProductLibrary([baseProduct], "IFP").length); });
test("27 product search excludes records absent from the canonical library", () => { const results = searchProductLibrary([baseProduct], "DEMO-NOT-IN-LIBRARY-999"); assert.equal(results.length, 0); assert.equal(searchProductLibrary([baseProduct], baseProduct.partNumber)[0].id, baseProduct.id); });
test("28 pricing retrieval excludes unapproved sources", () => assert.equal(isPriceEligibleForCosting({ ...current, sourceApproved: false }, { at: new Date("2026-08-02") }), false));
test("29 scanned source fails closed without OCR", async () => assert.match(await readFile(new URL("../app/domain/specification-extractor.mjs", import.meta.url), "utf8"), /not-configured/));
test("30 retry preserves idempotency", () => { const job = createProcessingJob({ kind: "Product Source", inputFingerprint: "sha", idempotencyKey: "same" }); assert.equal(advanceProcessingJob({ ...job, attempt: 1 }, "Loading Source", "retry").idempotencyKey, "same"); });
test("31 catalogue and datasheet enrich the same product", () => assert.equal(resolveProductIdentity(baseProduct, { ...baseProduct }).relationship, "Same product from another source"));
test("32 merge and split decisions are reversible", async () => { const sql = await readFile(new URL("../drizzle/0014_task9_fire_alarm_library.sql", import.meta.url), "utf8"); assert.match(sql, /product_identity_decisions/); assert.match(sql, /reversal_of_id/); });
test("33 source reprocessing preserves history", async () => { const sql = await readFile(new URL("../drizzle/0014_task9_fire_alarm_library.sql", import.meta.url), "utf8"); assert.match(sql, /product_versions/); assert.match(sql, /superseded_at/); });
test("34 Task 10 consumes reviewed canonical products only", async () => { const api = await readFile(new URL("../worker/product-matching-api.mjs", import.meta.url), "utf8"); assert.match(api, /library_products/); assert.match(api, /review_status/); });
test("35 Task 12 consumes current eligible prices only", async () => { const api = await readFile(new URL("../worker/pricing-api.mjs", import.meta.url), "utf8"); assert.match(api, /price_records/); assert.match(api, /downstream_use/); });
test("pilot taxonomy and processing stages are complete", () => { assert.equal(Object.values(FIRE_ALARM_TAXONOMY).flat().length, 51); assert.ok(ACCESSORY_QUANTITY_RULES.includes("One per loop")); assert.ok(PRODUCT_SOURCE_STAGES.includes("Resolving Identity")); assert.ok(PRICE_SOURCE_STAGES.includes("Extracting Validity")); });
test("legacy price helper remains fail closed", () => assert.equal(eligiblePrices([{ approvalStatus: "Approved", validUntil: null }]).length, 0));
