import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { buildTechnicalRequirementProfile, consolidateRequirements, detectRequirementConflicts, resolveApplicability } from "../app/domain/technical-requirement-engine.mjs";

const item = { id: "boq-1", itemNumber: "FA-01", description: "Addressable smoke detector", system: "Fire Alarm", category: "Detection Device", unit: "No.", quantity: 20, productFamily: "Addressable Smoke Detector", classificationConfidence: 95 };
const req = (overrides = {}) => ({ id: "r1", originalText: "Smoke detectors shall comply with EN 54-7.", normalizedRequirement: "smoke detectors shall comply with en 54 7", requirementType: "Mandatory", requirementCategory: "Standards", system: "Fire Alarm", category: "Detection Device", confidence: 92, sourceType: "Specification", source: { pageFrom: 4, clause: "2.3" }, attributes: [], standards: [{ body: "EN54", number: "7", confidence: 94 }], manufacturers: [], compatibility: [{ targetItem: "Addressable control panel protocol", confidence: 80 }], accessories: [], ...overrides });
test("separates suggested applicability from confirmed applicability", () => { assert.equal(resolveApplicability({ boqItem: item, requirement: req(), link: { status: "Suggested", confidence: 80 } }).status, "Suggested Applicable"); assert.equal(resolveApplicability({ boqItem: item, requirement: req(), link: { status: "Confirmed", evidence: ["Engineer review"] } }).status, "Confirmed Applicable"); });
test("consolidates equivalent requirements without losing source provenance", () => { const result = consolidateRequirements([req(), req({ id: "r2", sourceType: "BOQ", source: { row: 12 }, confidence: 80 })]); assert.equal(result.length, 1); assert.equal(result[0].sources.length, 2); assert.equal(result[0].governingSourceId, "r1"); });
test("detects blocking structured value conflicts", () => { const groups = consolidateRequirements([req({ attributes: [{ name: "Voltage", normalizedValue: 24, normalizedUnit: "V" }] }), req({ id: "r2", attributes: [{ name: "Voltage", normalizedValue: 12, normalizedUnit: "V" }] })]); const conflicts = detectRequirementConflicts(groups); assert.equal(conflicts[0].severity, "Critical"); assert.equal(conflicts[0].blocking, true); });
test("builds a traceable profile and blocks missing compatibility", () => { const profile = buildTechnicalRequirementProfile({ boqItem: item, requirements: [req({ compatibility: [] })], links: [{ requirementId: "r1", status: "Confirmed", evidence: ["Reviewed clause 2.3"] }] }); assert.equal(profile.applicableRequirements.length, 1); assert.equal(profile.suggestedRequirements.length, 0); assert.equal(profile.readiness.status, "Missing Critical Information"); assert.ok(profile.clarifications.some((entry) => /compatibility target/i.test(entry.question))); assert.match(profile.explanation, /matching readiness/i); });
test("marks derived accessories as derived and review-only", () => { const profile = buildTechnicalRequirementProfile({ boqItem: item, requirements: [req()], links: [{ requirementId: "r1", status: "Confirmed" }] }); const base = profile.derivedRequirements.find((entry) => /base/i.test(entry.statement)); assert.equal(base.factType, "Derived Fact"); assert.equal(base.reviewStatus, "Needs Review"); });
test("wires versioned persistence, APIs, audit, decisions and review UI", async () => { const [schema, worker, index, page] = await Promise.all([readFile(new URL("../db/schema.ts", import.meta.url), "utf8"), readFile(new URL("../worker/technical-requirement-api.mjs", import.meta.url), "utf8"), readFile(new URL("../worker/index.ts", import.meta.url), "utf8"), readFile(new URL("../app/page.tsx", import.meta.url), "utf8")]); for (const entity of ["requirementProfileVersions", "profileRequirementApplicability", "consolidatedProfileRequirements", "profileIssues", "requirementRules", "requirementRuleExecutions", "requirementProfileDecisions", "requirementProfileComparisons"]) assert.match(schema, new RegExp(`export const ${entity}`)); for (const contract of ["approve-readiness", "profile-applicability", "profile-issues", "Requirement Profile Generated", "input_fingerprint", "compare"]) assert.match(worker, new RegExp(contract)); assert.match(index, /handleTechnicalRequirementApi/); assert.match(page, /Generate profile/); });
