import test from "node:test";
import assert from "node:assert/strict";
import { derivePresalesWorkflow } from "../app/domain/presales-workflow-engine.mjs";
import { deriveProjectDashboard } from "../app/domain/dashboard-workflow-engine.mjs";

const project = { id: "p", name: "Pilot", organizationId: "o", systemDomain: "Fire Alarm" };
const complete = { documents: 2, classified: 2, boqItems: 2, specificationExtractions: 1, requirementProfiles: 2, matchedItems: 2, technicalApproved: 2, pricedItems: 2, commercialApproved: 2, finalReviewApproved: 2 };
const workflow = (facts = {}, projectPatch = {}) => derivePresalesWorkflow({ project: { ...project, ...projectPatch }, facts });

test("A new project is Draft at document intake", () => { const result = workflow(); assert.equal(result.lifecycleState, "Draft"); assert.equal(result.currentStageId, "intake"); assert.equal(result.readyForQuotation, false); });
test("B classified documents advance deterministically", () => { const pending = workflow({ documents: 2, classified: 1 }); const classified = workflow({ documents: 2, classified: 2 }); assert.equal(pending.stages.find((s) => s.id === "intake").status, "Needs Review"); assert.equal(classified.stages.find((s) => s.id === "intake").status, "Completed"); assert.ok(classified.progress > pending.progress); });
test("C BOQ extraction and review remain separate gates", () => { const reviewing = workflow({ documents: 1, classified: 1, boqItems: 4, extractionReview: 2, specificationExtractions: 1 }); assert.equal(reviewing.currentStageId, "extraction"); assert.match(reviewing.blockers.map((b) => b.message).join(" "), /2 BOQ item/); });
test("D price validity loss reverses quotation readiness", () => { assert.equal(workflow(complete).readyForQuotation, true); const expired = workflow({ ...complete, pricedItems: 1, missingPrices: 1 }); assert.equal(expired.readyForQuotation, false); assert.match(expired.blockers.map((b) => b.message).join(" "), /eligible current prices/); });
test("E incomplete technical approval fails closed", () => { const result = workflow({ ...complete, technicalApproved: 1, technicalPending: 1 }); assert.equal(result.readyForQuotation, false); assert.equal(result.stages.find((s) => s.id === "technical").status, "Needs Review"); });
test("F incomplete commercial approval fails closed", () => { const result = workflow({ ...complete, commercialApproved: 1, commercialPending: 1 }); assert.equal(result.readyForQuotation, false); assert.match(result.blockers.map((b) => b.message).join(" "), /commercial review/); });
test("G open blocking clarification fails closed", () => { const result = workflow({ ...complete, blockingClarifications: 1, openClarifications: 1 }); assert.equal(result.readyForQuotation, false); assert.match(result.blockers.map((b) => b.message).join(" "), /clarification/); });
test("H fully approved project is ready for quotation", () => { const result = workflow(complete); assert.equal(result.workflowStatus, "Ready for Quotation"); assert.equal(result.currentStageId, "quotation"); });
test("I won and lost are terminal lifecycle states", () => { for (const manualStatus of ["Won", "Lost"]) { const result = workflow(complete, { manualStatus }); assert.equal(result.lifecycleState, manualStatus); assert.equal(result.terminal, true); assert.equal(result.nextAction, null); assert.equal(result.readyForQuotation, false); } });
test("J on-hold suspends action without becoming terminal", () => { const result = workflow(complete, { manualStatus: "On Hold" }); assert.equal(result.suspended, true); assert.equal(result.terminal, false); assert.equal(result.nextAction, null); });
test("K dashboard exposes the exact canonical workflow projection", () => { const canonical = workflow(complete); const dashboard = deriveProjectDashboard({ facts: complete, project, role: "Estimator" }); assert.equal(dashboard.workflow.modelVersion, canonical.modelVersion); assert.equal(dashboard.workflow.progress, canonical.progress); assert.equal(dashboard.workflow.currentStageId, canonical.currentStageId); assert.equal(dashboard.workflow.readyForQuotation, canonical.readyForQuotation); assert.equal(dashboard.project.lifecycleState, canonical.lifecycleState); assert.equal(dashboard.project.workflowStage, canonical.workflowStage); });
test("historical learning facts cannot advance operational readiness", () => { const result = workflow({ historicalPrices: 500, historicalProducts: 1000 }); assert.equal(result.readyForQuotation, false); assert.equal(result.currentStageId, "intake"); });
