import json,urllib.request,hashlib,sqlite3,html,base64
from pathlib import Path
r=Path('.local-evidence/legend-comparison');wid='doc_3f857096-3152-408f-9c86-9296e4142ced';cid='doc_0de6f58b-7b48-46a2-92d3-aaef230c92b0';base='http://localhost:5173/api/documents/'+wid+'/drawing-extraction'
def get(url):return urllib.request.urlopen(url).read()
a=json.loads((r/'before.json').read_text());b=json.loads(get(base));(r/'after.json').write_text(json.dumps(b,indent=2));assert a['proposals']==b['proposals'];assert a['runs']==b['runs']
run=json.loads((r/'result-zoom-retry.json').read_text())['runId'];saved=json.loads(get(base+'/runs/'+run));(r/'saved-run.json').write_text(json.dumps(saved,indent=2));assert saved['result']==json.loads((r/'inspected-result.json').read_text());checks=[]
for im in saved['input_manifest']['images']:
 contents=get(base+'/runs/'+run+'/images/'+str(im['index']));sha=hashlib.sha256(contents).hexdigest();assert sha==im['sha256'];checks.append({'index':im['index'],'sha256':sha,'verified':True})
original=json.loads((r/'zoom-run-before-inspection.json').read_text());assert json.loads(original['raw_responses'])==saved['raw_responses'];assert all(p['assistantVisualInspection']['reviewedBy'] is None for p in saved['result']['comparisons'])
candidate=json.loads(get('http://localhost:5173/api/documents/'+cid+'/drawing-extraction'));defs=[p for p in candidate['proposals'] if p['extractionVersion']=='candidate-legend-visual-1'];assert len(defs)==20;assert all(p['reviewedBy'] is None and p['reviewStatus']=='Needs Review' for p in defs)
(r/'candidate-saved-definitions.json').write_text(json.dumps(defs,indent=2));(r/'verification.json').write_text(json.dumps({'wlcProposalsUnchanged':True,'previousUnderstandingRunsUnchanged':True,'candidateDefinitions':20,'candidateRuns':len(b['candidateComparisons']),'rawModelResponsesUnchangedAfterAssistantInspection':True,'imageChecks':checks},indent=2))
payload=json.loads((r/'request-zoom.json').read_text());esc=html.escape
def img(index,style=''):
 return '<img style="'+style+'" src="data:image/png;base64,'+payload['images'][index]['base64']+'">'
parts=['''<!doctype html><html><meta charset="utf-8"><title>Candidate Legend / WLC — provisional comparison</title><style>body{font:16px system-ui;color:#183047;background:#eef2f5;margin:0;padding:32px}main{max-width:1250px;margin:auto}section{background:white;border:1px solid #ccd6dd;border-radius:10px;padding:24px;margin:20px 0}h1{font-size:30px}h2{font-size:22px}.tag{background:#fff0c2;padding:12px;border-left:5px solid #b48012}.pair{display:grid;grid-template-columns:180px 1fr;gap:28px;align-items:start}.pair img{max-width:100%;image-rendering:auto}small{color:#596c7b}table{border-collapse:collapse;width:100%}td,th{text-align:left;border-bottom:1px solid #ddd;padding:10px}code{overflow-wrap:anywhere}summary{cursor:pointer;font-weight:600}p{line-height:1.55}@media(max-width:650px){.pair{grid-template-columns:1fr}body{padding:12px}}</style><main><h1>Candidate Legend ↔ WLC</h1><p class="tag">Unconfirmed candidate legend — drawing-number mismatch.<br>Reference: Unresolved · Revision compatibility: Unknown · Engineering review: Pending · Excluded from approved takeoff/pricing.</p>''']
parts+=['<section><h2>What the available legend adds</h2><p>20 Fire Alarm rows independently extracted into the existing LegendDefinition proposal pathway. Each retains its literal description, symbol/qualifier, row crop, symbol coordinates, document version and page. Other ELV tables are excluded.</p><p>WLC references <code>2401232-PC-AMS-T-00-ZZZ-002</code>. The candidate title block says <code>2401232-PC-AMS-DR-T-00-ZZZ-002</code>. The DR segment is preserved. Candidate revision <b>1 is visually observed</b>; the register revision remains <b>not recorded</b>.</p><p>Three provisional agreements and one unresolved comparison below are <b>Codex direct visual inspection</b>, not engineer approval. The actual vision provider received paired imagery and literal candidate descriptions in two completed runs. Its output was unreliable even with larger symbols; original responses are retained and are not adopted as verified matches.</p></section>']
for pair in saved['result']['comparisons']:
 obs=pair['assistantVisualInspection'];parts+=['<section><h2>'+esc(pair['literalDescription'])+'</h2><div class="pair"><div><h3>WLC occurrence</h3>'+img(pair['wlcImageIndex'])+'</div><div><h3>Candidate legend row</h3>'+img(pair['legendImageIndex'])+'</div></div><p><b>'+esc(obs['outcome'])+'</b></p><p>'+esc(obs['matchBasis'])+'</p><p><b>Ambiguity:</b> '+esc(obs['ambiguity'])+'</p><small>Needs Review · No human decision recorded. Source images '+str(pair['wlcImageIndex'])+' / '+str(pair['legendImageIndex'])+'; exact source version/page/coordinates retained in saved-run.json.</small><details><summary>Original model response (unreliable)</summary><p>'+esc(pair['modelAssessment'])+'</p></details></section>']
parts+=['<section><h2>Independent Fire Alarm legend extraction — 20 rows</h2><p>Page 1 · candidate version <code>ver_47d5b443-74a1-4643-a29f-c8f7b4fdc5e6</code> · all Needs Review.</p>']
for entry in payload['entries']:
 parts+=['<details><summary>'+str(entry['sequence'])+'. '+esc(entry['description'])+'</summary>'+img(entry['imageIndex'],'max-width:100%')+'<p>Literal label: '+esc(entry['label'] or '(graphical symbol; no abbreviation)')+'; qualifiers: '+esc(entry['qualifiers'] or '(none separately transcribed)')+'</p><small>Canonical PDF lower-left coordinates: '+esc(json.dumps(entry['boundingBox']))+'</small></details>']
parts+=['</section><section><h2>Persistence and remaining confirmation</h2><p>29/29 latest-run image hashes verified through protected API reopening. All prior WLC findings and understanding runs remain unchanged, including FACP room, title/revision, cable evidence and circuit-status restraint. Candidate extraction remains 20 rows after rerun. Two completed candidate runs plus one failed attempt are retained separately. The failed retry hit an empty insertion batch when the same legend rows already existed; this was fixed without duplicating rows.</p><p>52 focused tests passed. Whole-project TypeScript still reports the same seven existing app/page.tsx errors; no errors were reported in the changed files.</p><p><b>Engineer confirmation needed:</b> confirm in a controlled correction or documented equivalence that the WLC note without DR intends <code>2401232-PC-AMS-DR-T-00-ZZZ-002</code>, specifically its applicable revision, and review the candidate-derived symbol meanings. Model reliability also remains a limitation; linkage confirmation alone does not validate model interpretations.</p><p>Saved comparison run: <code>'+run+'</code>. Full source and model provenance: saved-run.json. Independent definitions: candidate-saved-definitions.json. Verification: verification.json.</p></section></main></html>']
(r/'comparison.html').write_text(''.join(parts));print('Verified unchanged WLC state; 20 definitions; 29 image hashes; saved comparisons and raw responses.')
