CREATE TABLE `product_reference_registry_v2` (
  `table_name` text NOT NULL,
  `product_column` text NOT NULL,
  `strategy` text NOT NULL CHECK (`strategy` IN ('MOVE','RESOLVE','BLOCK','KEEP')),
  `module_name` text NOT NULL,
  `enabled` integer NOT NULL DEFAULT 1,
  `registry_version` integer NOT NULL DEFAULT 2,
  `created_at` text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`table_name`,`product_column`)
);
INSERT INTO `product_reference_registry_v2` (`table_name`,`product_column`,`strategy`,`module_name`) VALUES
 ('product_source_evidence','product_id','MOVE','Product Library'),
 ('price_records','product_id','MOVE','Pricing Sources'),
 ('product_versions','product_id','KEEP','Product Library'),
 ('product_variants','base_product_id','BLOCK','Product Library'),
 ('product_aliases','product_id','BLOCK','Product Library'),
 ('regional_part_numbers','product_id','BLOCK','Product Library'),
 ('product_attributes','product_id','BLOCK','Product Library'),
 ('product_certifications','product_id','BLOCK','Product Library'),
 ('product_compatibility','source_product_id','BLOCK','Product Library'),
 ('product_compatibility','target_product_id','BLOCK','Product Library'),
 ('product_accessories','product_id','BLOCK','Product Library'),
 ('product_accessories','accessory_product_id','BLOCK','Product Library'),
 ('product_packages','product_id','BLOCK','Product Library'),
 ('product_package_components','component_product_id','BLOCK','Product Library'),
 ('product_documents','product_id','BLOCK','Product Library'),
 ('product_lifecycle_events','product_id','BLOCK','Product Library'),
 ('supplier_products','product_id','BLOCK','Supplier Library'),
 ('supplier_quote_lines','product_id','BLOCK','Supplier Library'),
 ('price_conflicts','product_id','BLOCK','Pricing Sources'),
 ('product_match_candidates','product_id','RESOLVE','Matching'),
 ('pricing_lines','product_id','RESOLVE','Pricing'),
 ('identity_resolution_candidates','product_id','KEEP','Identity Resolution'),
 ('product_conflicts','product_id','KEEP','Identity Resolution'),
 ('product_identity_decisions','left_product_id','KEEP','Identity Resolution'),
 ('product_identity_decisions','right_product_id','KEEP','Identity Resolution'),
 ('library_products','superseded_by_product_id','KEEP','Canonical Resolver'),
 ('identity_proposal_reviews','canonical_product_id','KEEP','Identity Governance'),
 ('governed_identity_decisions','canonical_product_id','KEEP','Identity Governance'),
 ('governed_identity_decisions','non_target_product_id','KEEP','Identity Governance'),
 ('manufacturer_order_code_observations','canonical_product_id','KEEP','Identity Governance'),
 ('manufacturer_order_code_observations','original_product_id','KEEP','Identity Governance'),
 ('identity_reference_moves','from_product_id','KEEP','Identity Governance'),
 ('identity_reference_moves','to_product_id','KEEP','Identity Governance'),
 ('identity_mutation_guards','target_product_id','KEEP','Identity Governance'),
 ('identity_mutation_guards','non_target_product_id','KEEP','Identity Governance'),
 ('identity_mutation_guards','reference_owner_product_id','KEEP','Identity Governance'),
 ('identity_reference_guards','expected_owner_product_id','KEEP','Identity Governance'),
 ('canonical_product_resolution_audit','requested_product_id','KEEP','Canonical Resolver'),
 ('canonical_product_resolution_audit','canonical_product_id','KEEP','Canonical Resolver');

UPDATE `identity_schema_compatibility` SET schema_version=22,minimum_worker_version=22,maximum_worker_version=22,migration_checksum='migration-0022-complete-reference-registry' WHERE component='Identity Resolution';
