import { chromium } from "playwright";
const BASE = "http://localhost:4183";
const PROJECT = "project_ae501b85-9c12-4332-bf8e-787c90f2d388";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1680, height: 1050 } });
await page.goto(`${BASE}/?project=${PROJECT}&workspace=BOQ`, { waitUntil: "domcontentloaded" });
await page.locator("tbody tr").first().waitFor({ timeout: 60000 });
await page.waitForTimeout(2500);
const url = new URL(page.url());
console.log("URL params:", url.searchParams.toString());
const buttons = await page.locator("button").allInnerTexts();
console.log("buttons containing 'Duplicate' or 'filter':", JSON.stringify(buttons.filter((text) => /duplicate/i.test(text))));
console.log("button count:", buttons.length);
console.log("all buttons sample:", JSON.stringify(buttons.slice(0, 40)));
const text = await page.locator("body").innerText();
const idx = text.indexOf("Possible Duplicates");
console.log("body text around 'Possible Duplicates':", JSON.stringify(text.slice(Math.max(0, idx - 200), idx + 200)));
await page.screenshot({ path: new URL("./out/probe.png", import.meta.url).pathname, fullPage: true });
await browser.close();
